// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5

// Note: Specifying the triple seems to be necessary for `update_cc_test_checks.py` to work
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -emit-llvm -fbounds-safety -fbounds-safety-bringup-missing-checks=compound_literal_init -Wno-bounds-attributes-init-list-side-effect -o - %s | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -emit-llvm -x objective-c -fexperimental-bounds-safety-objc -fbounds-safety -fbounds-safety-bringup-missing-checks=compound_literal_init -Wno-bounds-attributes-init-list-side-effect %s -o - | FileCheck %s

#include <ptrcheck.h>

struct sb {
  int count;
  char* __sized_by(count) buf;
};
void consume_sb(struct sb);
void consume_sb_arr(struct sb (*arr)[]);

struct nested_sb {
  struct sb nested;
  int other;
};

struct nested_and_outer_sb {
  struct sb nested;
  int other;
  int count;
  char* __sized_by(count) buf;
};


int get_int(void);

struct sb_with_other_data {
  int count;
  char* __sized_by(count) buf;
  int other;
};
struct no_attr_with_other_data {
  int count;
  char* buf;
  int other;
};
_Static_assert(sizeof(struct sb_with_other_data) ==
               sizeof(struct no_attr_with_other_data), "size mismatch");
void consume_sb_with_other_data_arr(struct sb_with_other_data (*arr)[]);

union TransparentUnion {
  struct sb_with_other_data sb;
  struct no_attr_with_other_data no_sb;
} __attribute__((__transparent_union__));

void receive_transparent_union(union TransparentUnion);

// NOTE: We currently don't test globals because those don't generate bounds
// checks. We currently rely on Sema checks to prevent all invalid externally
// counted pointers. This only works because global initializers must be
// constant evaluable.

// =============================================================================
// Tests with __bidi_indexable source ptr
//
// These are more readable due to the lack of BoundsSafetyPromotionExpr
// =============================================================================

void assign_via_ptr(struct sb* ptr, int new_count,
                    char* __bidi_indexable new_ptr) {
  *ptr = (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void assign_operator(int new_count, char* __bidi_indexable new_ptr) {
  struct sb new;
  new = (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}


void local_var_init(int new_count, char* __bidi_indexable new_ptr) {
  struct sb new = (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void call_arg(int new_count, char* __bidi_indexable new_ptr) {
  consume_sb((struct sb) {
    .count = new_count,
    .buf = new_ptr
  });
}

struct sb return_sb(int new_count, char* __bidi_indexable new_ptr) {
  return (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void construct_not_used(int new_count, char* __bidi_indexable new_ptr) {
  (void)(struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void assign_via_ptr_nullptr(struct sb* ptr, int new_count) {
  *ptr = (struct sb) {
    .count = new_count,
    .buf = 0x0
  };
}

void assign_via_ptr_nested(struct nested_sb* ptr,
                           char* __bidi_indexable new_ptr,
                           int new_count) {
  *ptr = (struct nested_sb) {
    .nested = {.buf = new_ptr, .count = new_count },
    .other = 0x0
  };
}

void assign_via_ptr_nested_v2(struct nested_sb* ptr,
                              char* __bidi_indexable new_ptr,
                              int new_count) {
  *ptr = (struct nested_sb) {
    .nested = (struct sb){.buf = new_ptr, .count = new_count },
    .other = 0x0
  };
}

void assign_via_ptr_nested_v3(struct nested_and_outer_sb* ptr,
                              char* __bidi_indexable new_ptr,
                              int new_count) {
  *ptr = (struct nested_and_outer_sb) {
    .nested = (struct sb){.buf = new_ptr, .count = new_count },
    .other = 0x0,
    .buf = new_ptr,
    .count = new_count
  };
}

void array_of_struct_init(char* __bidi_indexable new_ptr,
                          int new_count) {
  struct sb arr[] = (struct sb[]) {
    {.count = new_count, .buf = new_ptr},
    {.count = 0x0, .buf = 0x0}
  };
  consume_sb_arr(&arr);
}


void assign_via_ptr_other_data_side_effect(struct sb_with_other_data* ptr,
                                           int new_count,
                                           char* __bidi_indexable new_ptr) {
  *ptr = (struct sb_with_other_data) {
    .count = new_count,
    .buf = new_ptr,
    // Side effect. Generates a warning but it is suppressed for this test
    .other = get_int()
  };
}

void assign_via_ptr_other_data_side_effect_zero_ptr(struct sb_with_other_data* ptr,
                                           int new_count,
                                           char* __bidi_indexable new_ptr) {
  *ptr = (struct sb_with_other_data) {
    .count = new_count,
    .buf = 0x0,
    // Side effect. Generates a warning but it is suppressed for this test
    .other = get_int()
  };
}

void call_arg_transparent_union(int new_count,
                                char* __bidi_indexable new_ptr) {
  receive_transparent_union(
    (struct sb_with_other_data) {
      .count = new_count,
      .buf = new_ptr,
      .other = 0x0
    }
  );
}

void call_arg_transparent_union_untransparently(int new_count,
                                char* __bidi_indexable new_ptr) {
  receive_transparent_union(
    (union TransparentUnion) {
      .sb = {
        .count = new_count,
        .buf = new_ptr,
        .other = 0x0
      }
    }
  );
}

// =============================================================================
// Tests with __sized_by source ptr
//
// These are less readable due to the BoundsSafetyPromotionExpr
// =============================================================================
void assign_via_ptr_from_ptr(struct sb* ptr) {
  *ptr = (struct sb) {
    .count = ptr->count,
    .buf = ptr->buf
  };
}

void assign_via_ptr_from_sb(struct sb* ptr, int new_count,
                            char* __sized_by(new_count) new_ptr) {
  *ptr = (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void assign_operator_from_sb(int new_count,
                             char* __sized_by(new_count) new_ptr) {
  struct sb new;
  new = (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}


void local_var_init_from_sb(int new_count,
                            char* __sized_by(new_count) new_ptr) {
  struct sb new = (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void call_arg_from_sb(int new_count,
                      char* __sized_by(new_count) new_ptr) {
  consume_sb((struct sb) {
    .count = new_count,
    .buf = new_ptr
  });
}

struct sb return_sb_from_sb(int new_count,
                            char* __sized_by(new_count) new_ptr) {
  return (struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void construct_not_used_from_sb(int new_count,
                                char* __sized_by(new_count) new_ptr) {
  (void)(struct sb) {
    .count = new_count,
    .buf = new_ptr
  };
}

void assign_via_ptr_nested_from_sb(struct nested_sb* ptr,
                                   char* __sized_by(new_count) new_ptr,
                                   int new_count) {
  *ptr = (struct nested_sb) {
    .nested = {.buf = new_ptr, .count = new_count },
    .other = 0x0
  };
}

void assign_via_ptr_nested_v2_from_sb(struct nested_sb* ptr,
                                      char* __sized_by(new_count)new_ptr,
                                      int new_count) {
  *ptr = (struct nested_sb) {
    .nested = (struct sb){.buf = new_ptr, .count = new_count },
    .other = 0x0
  };
}

void array_of_struct_init_from_sb(char* __sized_by(new_count) new_ptr,
                                  int new_count) {
  struct sb arr[] = (struct sb[]) {
    {.count = new_count, .buf = new_ptr},
    {.count = 0x0, .buf = 0x0}
  };
  consume_sb_arr(&arr);
}

void assign_via_ptr_other_data_side_effect_from_sb(struct sb_with_other_data* ptr,
                                                   int new_count,
                                                   char* __sized_by(new_count) new_ptr) {
  *ptr = (struct sb_with_other_data) {
    .count = new_count,
    .buf = new_ptr,
    // Side effect. Generates a warning but it is suppressed for this test
    .other = get_int()
  };
}

void assign_via_ptr_other_data_side_effect_zero_ptr_from_sb(struct sb_with_other_data* ptr,
                                           int new_count,
                                           char* __sized_by(new_count) new_ptr) {
  *ptr = (struct sb_with_other_data) {
    .count = new_count,
    .buf = 0x0,
    // Side effect. Generates a warning but it is suppressed for this test
    .other = get_int()
  };
}

void call_arg_transparent_union_from_sb(int new_count,
                                        char* __bidi_indexable new_ptr) {
  receive_transparent_union(
    (struct sb_with_other_data) {
      .count = new_count,
      .buf = new_ptr,
      .other = 0x0
    }
  );
}


void call_arg_transparent_union_untransparently_from_sb(int new_count,
                                char* __bidi_indexable new_ptr) {
  receive_transparent_union(
    (union TransparentUnion) {
      .sb = {
        .count = new_count,
        .buf = new_ptr,
        .other = 0x0
      }
    }
  );
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
