// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 4
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -Wno-bounds-safety-init-list -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -Wno-bounds-safety-init-list -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

void foo(int *__counted_by_or_null(len) p, int len);

// CHECK-LABEL: define dso_local void @caller_1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @foo(ptr noundef null, i32 noundef 2) #[[ATTR5:[0-9]+]]
// CHECK-NEXT:    ret void
//
void caller_1() {
  foo(0, 2);
}

// CHECK-LABEL: define dso_local void @caller_2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @foo(ptr noundef null, i32 noundef 0) #[[ATTR5]]
// CHECK-NEXT:    ret void
//
void caller_2() {
  foo(0, 0);
}

// rdar://118117905
void caller_3(int *__counted_by_or_null(len) p, int len) {
  foo(p, len);
}

void caller_4() {
    int i = 0;
    foo(&i, -1);
}

void caller_5() {
    int i = 0;
    foo(&i, 2);
}

void caller_6(int *__counted_by(len) p, int len) {
  foo(p, len);
}

void caller_7(int *__bidi_indexable p, int len) {
  foo(p, len);
}

void caller_8(int *__single p, int len) {
  foo(p, len);
}

void bar(int *__counted_by(*len) *out, int *len);

// CHECK-LABEL: define dso_local void @caller_9(
// CHECK-SAME: ptr noundef [[OUT:%.*]], ptr noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @bar(ptr noundef [[OUT]], ptr noundef [[LEN]]) #[[ATTR5]]
// CHECK-NEXT:    ret void
//
void caller_9(int *__counted_by(*len) *out, int *len){
    bar(out, len);
}

int *__counted_by_or_null(len) caller_10(int len) {
    int count;
    int *__counted_by_or_null(count) p;
    bar(&p, &count);
    p = p; // workaround for missing return bounds check
    count = len;
    return p;
}

