// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @f_inout_count(
// CHECK-SAME: ptr nofree noundef readnone captures(none) [[BUF:%.*]], ptr nofree noundef readnone captures(none) [[OUT_LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void f_inout_count(int *__counted_by(*out_len) buf, int *out_len) {}

// CHECK-LABEL: define dso_local void @success(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void success() {
  int arr[10];
  int len = 10;
  f_inout_count(arr, &len);
}

void fail() {
  int arr[10];
  int len = 11;
  f_inout_count(arr, &len);
}

void pass_out_len(int *__counted_by(*out_len) arr, int *out_len) {
  f_inout_count(arr, out_len);
}

void pass_addr_of_len(int *__counted_by(len) arr, int len) {
  f_inout_count(arr, &len);
}
