; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define void @test(ptr %0, ptr %1, double %2, ptr %3) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[TMP0:%.*]], ptr [[TMP1:%.*]], double [[TMP2:%.*]], ptr [[TMP3:%.*]]) {
; CHECK-NEXT:    br i1 true, label %[[VECTOR_PH:.*]], label %[[DOTPREHEADER511:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP5:%.*]] = load double, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = fadd double [[TMP2]], 0.000000e+00
; CHECK-NEXT:    [[TMP11:%.*]] = fadd double [[TMP10]], 1.000000e+00
; CHECK-NEXT:    [[TMP17:%.*]] = load double, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP22:%.*]] = load double, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <2 x double> poison, double [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP68:%.*]] = insertelement <2 x double> [[TMP12]], double [[TMP17]], i64 1
; CHECK-NEXT:    [[TMP69:%.*]] = fmul <2 x double> [[TMP68]], zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <2 x double> <double 0.000000e+00, double poison>, double [[TMP2]], i64 1
; CHECK-NEXT:    [[TMP14:%.*]] = fmul <2 x double> [[TMP69]], [[TMP13]]
; CHECK-NEXT:    [[TMP15:%.*]] = fmul <2 x double> [[TMP14]], [[TMP13]]
; CHECK-NEXT:    [[TMP26:%.*]] = insertelement <2 x double> poison, double [[TMP2]], i64 0
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <2 x double> [[TMP26]], <2 x double> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x double> [[TMP69]], <2 x double> <double 0.000000e+00, double poison>, <2 x i32> <i32 2, i32 0>
; CHECK-NEXT:    [[TMP19:%.*]] = fmul <2 x double> [[TMP27]], [[TMP18]]
; CHECK-NEXT:    [[TMP20:%.*]] = fadd contract <2 x double> [[TMP19]], zeroinitializer
; CHECK-NEXT:    [[TMP21:%.*]] = fmul double [[TMP22]], 0.000000e+00
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <2 x double> [[TMP13]], <2 x double> poison, <2 x i32> <i32 1, i32 1>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <2 x double> [[TMP14]], <2 x double> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <2 x double> [[TMP23]], double [[TMP21]], i64 1
; CHECK-NEXT:    [[TMP30:%.*]] = fmul <2 x double> [[TMP25]], [[TMP24]]
; CHECK-NEXT:    [[TMP28:%.*]] = insertelement <2 x double> <double poison, double 0.000000e+00>, double [[TMP11]], i64 0
; CHECK-NEXT:    [[TMP36:%.*]] = fadd <2 x double> [[TMP15]], [[TMP28]]
; CHECK-NEXT:    [[TMP31:%.*]] = fadd <2 x double> [[TMP30]], zeroinitializer
; CHECK-NEXT:    [[TMP29:%.*]] = fmul double [[TMP5]], 0.000000e+00
; CHECK-NEXT:    [[TMP39:%.*]] = fmul double [[TMP29]], 0.000000e+00
; CHECK-NEXT:    [[TMP48:%.*]] = insertelement <2 x double> [[TMP69]], double [[TMP39]], i64 1
; CHECK-NEXT:    [[TMP49:%.*]] = fadd <2 x double> [[TMP48]], zeroinitializer
; CHECK-NEXT:    [[TMP33:%.*]] = fmul double [[TMP2]], [[TMP17]]
; CHECK-NEXT:    [[TMP34:%.*]] = fadd double [[TMP33]], 0.000000e+00
; CHECK-NEXT:    br label %[[DOTPREHEADER511]]
; CHECK:       [[_PREHEADER511:.*:]]
; CHECK-NEXT:    [[DOTSROA_9_0:%.*]] = phi double [ [[TMP34]], %[[VECTOR_PH]] ], [ 0.000000e+00, [[TMP4:%.*]] ]
; CHECK-NEXT:    [[TMP35:%.*]] = phi <2 x double> [ [[TMP20]], %[[VECTOR_PH]] ], [ zeroinitializer, [[TMP4]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = phi <2 x double> [ [[TMP36]], %[[VECTOR_PH]] ], [ zeroinitializer, [[TMP4]] ]
; CHECK-NEXT:    [[TMP50:%.*]] = phi <2 x double> [ [[TMP31]], %[[VECTOR_PH]] ], [ zeroinitializer, [[TMP4]] ]
; CHECK-NEXT:    [[TMP54:%.*]] = phi <2 x double> [ [[TMP49]], %[[VECTOR_PH]] ], [ zeroinitializer, [[TMP4]] ]
; CHECK-NEXT:    br i1 true, label %[[BB31:.*]], [[DOTPREHEADER498:label %.*]]
; CHECK:       [[BB31]]:
; CHECK-NEXT:    [[TMP40:%.*]] = load double, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP52:%.*]] = fmul double [[DOTSROA_9_0]], [[TMP2]]
; CHECK-NEXT:    [[TMP38:%.*]] = load <2 x double>, ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP53:%.*]] = shufflevector <2 x double> [[TMP38]], <2 x double> poison, <2 x i32> <i32 1, i32 0>
; CHECK-NEXT:    [[TMP58:%.*]] = extractelement <2 x double> [[TMP53]], i64 1
; CHECK-NEXT:    [[TMP59:%.*]] = extractelement <2 x double> [[TMP53]], i64 0
; CHECK-NEXT:    [[TMP60:%.*]] = extractelement <2 x double> [[TMP32]], i64 0
; CHECK-NEXT:    [[TMP47:%.*]] = fmul double [[TMP60]], [[TMP59]]
; CHECK-NEXT:    [[TMP41:%.*]] = fmul <2 x double> [[TMP35]], [[TMP53]]
; CHECK-NEXT:    [[TMP42:%.*]] = fmul <2 x double> [[TMP32]], [[TMP38]]
; CHECK-NEXT:    [[TMP43:%.*]] = fadd <2 x double> [[TMP41]], [[TMP42]]
; CHECK-NEXT:    [[TMP51:%.*]] = insertelement <2 x double> <double 0.000000e+00, double poison>, double [[TMP40]], i64 1
; CHECK-NEXT:    [[TMP37:%.*]] = fmul <2 x double> [[TMP50]], [[TMP51]]
; CHECK-NEXT:    [[TMP44:%.*]] = fadd <2 x double> [[TMP43]], [[TMP37]]
; CHECK-NEXT:    [[TMP65:%.*]] = insertelement <2 x double> poison, double [[TMP2]], i64 0
; CHECK-NEXT:    [[TMP45:%.*]] = insertelement <2 x double> [[TMP65]], double [[TMP52]], i64 1
; CHECK-NEXT:    [[TMP46:%.*]] = fadd <2 x double> [[TMP44]], [[TMP45]]
; CHECK-NEXT:    [[TMP66:%.*]] = fadd <2 x double> [[TMP46]], zeroinitializer
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <2 x double> [[TMP38]], <2 x double> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP56:%.*]] = fmul <2 x double> [[TMP54]], [[TMP55]]
; CHECK-NEXT:    [[TMP57:%.*]] = insertelement <2 x double> poison, double [[TMP2]], i64 1
; CHECK-NEXT:    [[TMP61:%.*]] = insertelement <2 x double> [[TMP57]], double [[TMP47]], i64 0
; CHECK-NEXT:    [[TMP62:%.*]] = fadd <2 x double> [[TMP56]], [[TMP61]]
; CHECK-NEXT:    [[TMP73:%.*]] = shufflevector <2 x double> [[TMP35]], <2 x double> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[TMP74:%.*]] = insertelement <2 x double> [[TMP73]], double [[DOTSROA_9_0]], i64 1
; CHECK-NEXT:    [[TMP63:%.*]] = fmul <2 x double> [[TMP74]], zeroinitializer
; CHECK-NEXT:    [[TMP64:%.*]] = fadd <2 x double> [[TMP62]], [[TMP63]]
; CHECK-NEXT:    [[TMP75:%.*]] = fadd <2 x double> [[TMP64]], zeroinitializer
; CHECK-NEXT:    [[TMP76:%.*]] = fadd <2 x double> [[TMP75]], splat (double 1.000000e+00)
; CHECK-NEXT:    br [[DOTPREHEADER498]]
; CHECK:       [[_PREHEADER498:.*:]]
; CHECK-NEXT:    [[DOTSROA_18924_0:%.*]] = phi double [ [[TMP58]], %[[BB31]] ], [ 0.000000e+00, %[[DOTPREHEADER511]] ]
; CHECK-NEXT:    [[TMP67:%.*]] = phi <2 x double> [ [[TMP66]], %[[BB31]] ], [ zeroinitializer, %[[DOTPREHEADER511]] ]
; CHECK-NEXT:    [[TMP70:%.*]] = phi <2 x double> [ [[TMP76]], %[[BB31]] ], [ zeroinitializer, %[[DOTPREHEADER511]] ]
; CHECK-NEXT:    [[TMP71:%.*]] = extractelement <2 x double> [[TMP70]], i64 0
; CHECK-NEXT:    store double [[TMP71]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[DOTSROA_10918_0__SROA_IDX919:%.*]] = getelementptr i8, ptr [[TMP1]], i64 8
; CHECK-NEXT:    store <2 x double> [[TMP67]], ptr [[DOTSROA_10918_0__SROA_IDX919]], align 8
; CHECK-NEXT:    [[DOTSROA_14921_0__SROA_IDX922:%.*]] = getelementptr i8, ptr [[TMP1]], i64 24
; CHECK-NEXT:    [[TMP72:%.*]] = extractelement <2 x double> [[TMP70]], i64 1
; CHECK-NEXT:    store double [[TMP72]], ptr [[DOTSROA_14921_0__SROA_IDX922]], align 8
; CHECK-NEXT:    store double [[DOTSROA_18924_0]], ptr [[TMP0]], align 8
; CHECK-NEXT:    ret void
;
  br i1 true, label %vector.ph, label %.preheader511

vector.ph:
  %5 = load double, ptr %0, align 8
  %6 = fmul double %5, 0.000000e+00
  %7 = fadd double %6, 0.000000e+00
  %8 = fmul double %6, 0.000000e+00
  %9 = fmul double %8, 0.000000e+00
  %10 = fadd double %2, 0.000000e+00
  %11 = fadd double %10, 1.000000e+00
  %12 = fadd double %9, %11
  %13 = fmul double %2, 0.000000e+00
  %14 = fadd contract double %13, 0.000000e+00
  %15 = fmul double %6, %2
  %16 = fadd contract double %15, 0.000000e+00
  %17 = load double, ptr %1, align 8
  %18 = fmul double %17, 0.000000e+00
  %19 = fmul double %18, %2
  %20 = fmul double %2, %19
  %21 = fadd double %20, 0.000000e+00
  %22 = load double, ptr %0, align 8
  %23 = fmul double %22, 0.000000e+00
  %24 = fmul double %2, %23
  %25 = fadd double %24, 0.000000e+00
  %26 = fmul double %5, 0.000000e+00
  %27 = fmul double %26, 0.000000e+00
  %28 = fadd double %27, 0.000000e+00
  %29 = fmul double %2, %17
  %30 = fadd double %29, 0.000000e+00
  br label %.preheader511

.preheader511:
  %.sroa.9.0 = phi double [ %30, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.7.0 = phi double [ %28, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.6887.0 = phi double [ %25, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.5.0 = phi double [ %21, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.4886.0 = phi double [ %16, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.3.0 = phi double [ %14, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.2885.0 = phi double [ %12, %vector.ph ], [ 0.000000e+00, %4 ]
  %.sroa.0884.0 = phi double [ %7, %vector.ph ], [ 0.000000e+00, %4 ]
  br i1 true, label %31, label %.preheader498

31:
  %32 = getelementptr i8, ptr %3, i64 8
  %33 = load double, ptr %3, align 8
  %34 = fmul double %.sroa.0884.0, %33
  %35 = load double, ptr %32, align 8
  %36 = fmul double %.sroa.2885.0, %35
  %37 = fadd double %34, %36
  %38 = fmul double %.sroa.4886.0, 0.000000e+00
  %39 = fadd double %37, %38
  %40 = fadd double %39, 0.000000e+00
  %41 = fadd double %40, 1.000000e+00
  %42 = fmul double %.sroa.2885.0, %33
  %43 = fmul double %.sroa.3.0, %35
  %44 = fadd double %42, %43
  %45 = fmul double %.sroa.5.0, 0.000000e+00
  %46 = fadd double %44, %45
  %47 = fadd double %46, %2
  %48 = fadd double %47, 0.000000e+00
  %49 = fmul double %.sroa.4886.0, %33
  %50 = fmul double %.sroa.5.0, %35
  %51 = fadd double %49, %50
  %52 = load double, ptr %0, align 8
  %53 = fmul double %.sroa.6887.0, %52
  %54 = fadd double %51, %53
  %55 = fmul double %.sroa.9.0, %2
  %56 = fadd double %54, %55
  %57 = fadd double %56, 0.000000e+00
  %58 = fmul double %.sroa.7.0, %33
  %59 = fadd double %58, %2
  %60 = fmul double %.sroa.9.0, 0.000000e+00
  %61 = fadd double %59, %60
  %62 = fadd double %61, 0.000000e+00
  %63 = fadd double %62, 1.000000e+00
  br label %.preheader498

.preheader498:
  %.sroa.0913.0 = phi double [ %41, %31 ], [ 0.000000e+00, %.preheader511 ]
  %.sroa.6915.0 = phi double [ %48, %31 ], [ 0.000000e+00, %.preheader511 ]
  %.sroa.10918.0 = phi double [ %57, %31 ], [ 0.000000e+00, %.preheader511 ]
  %.sroa.14921.0 = phi double [ %63, %31 ], [ 0.000000e+00, %.preheader511 ]
  %.sroa.18924.0 = phi double [ %33, %31 ], [ 0.000000e+00, %.preheader511 ]
  store double %.sroa.0913.0, ptr %1, align 8
  %.sroa.6915.0..sroa_idx916 = getelementptr i8, ptr %1, i64 8
  store double %.sroa.6915.0, ptr %.sroa.6915.0..sroa_idx916, align 8
  %.sroa.10918.0..sroa_idx919 = getelementptr i8, ptr %1, i64 16
  store double %.sroa.10918.0, ptr %.sroa.10918.0..sroa_idx919, align 8
  %.sroa.14921.0..sroa_idx922 = getelementptr i8, ptr %1, i64 24
  store double %.sroa.14921.0, ptr %.sroa.14921.0..sroa_idx922, align 8
  store double %.sroa.18924.0, ptr %0, align 8
  ret void
}
