; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s

define double @test(ptr %p, double %d) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: ptr [[P:%.*]], double [[D:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = fdiv double 0.000000e+00, [[D]]
; CHECK-NEXT:    [[TMP7:%.*]] = fmul double [[TMP2]], 0.000000e+00
; CHECK-NEXT:    [[TMP4:%.*]] = fmul double [[TMP7]], 0.000000e+00
; CHECK-NEXT:    [[TMP5:%.*]] = fdiv double [[TMP4]], [[D]]
; CHECK-NEXT:    [[TMP6:%.*]] = fdiv double 0.000000e+00, [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = fmul double [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP13:%.*]] = fmul double [[TMP8]], 0.000000e+00
; CHECK-NEXT:    [[TMP9:%.*]] = fsub double 0.000000e+00, [[TMP13]]
; CHECK-NEXT:    store double [[TMP9]], ptr [[P]], align 8
; CHECK-NEXT:    [[TMP15:%.*]] = fmul double [[TMP7]], 0.000000e+00
; CHECK-NEXT:    [[TMP10:%.*]] = fdiv double [[TMP15]], [[D]]
; CHECK-NEXT:    [[TMP11:%.*]] = fmul double [[TMP10]], [[TMP6]]
; CHECK-NEXT:    [[TMP12:%.*]] = fmul double [[TMP11]], 0.000000e+00
; CHECK-NEXT:    [[TMP14:%.*]] = fsub double 0.000000e+00, [[TMP12]]
; CHECK-NEXT:    ret double [[TMP14]]
;
  %2 = fdiv double 0.000000e+00, %d
  %3 = fmul double %2, 0.000000e+00
  %4 = fmul double %3, 0.000000e+00
  %5 = fdiv double %4, %d
  %6 = fdiv double 0.000000e+00, %4
  %7 = fmul double %5, %6
  %8 = fmul double %7, 0.000000e+00
  %9 = fsub double 0.000000e+00, %8
  store double %9, ptr %p, align 8
  %10 = fmul double %3, 0.000000e+00
  %11 = fdiv double %10, %d
  %12 = fmul double %11, %6
  %13 = fmul double %12, 0.000000e+00
  %14 = fsub double 0.000000e+00, %13
  ret double %14
}

define float @test1() {
; CHECK-LABEL: define float @test1() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = fadd float 0.000000e+00, 0.000000e+00
; CHECK-NEXT:    [[TMP1:%.*]] = fmul float [[TMP0]], 0.000000e+00
; CHECK-NEXT:    [[TMP2:%.*]] = fadd float 0.000000e+00, [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = fadd float 0.000000e+00, [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x float> poison, float [[TMP1]], i64 0
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <2 x float> [[TMP4]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = fmul <2 x float> zeroinitializer, [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = fadd <2 x float> zeroinitializer, [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = fadd <2 x float> zeroinitializer, [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x float> poison, float [[TMP3]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <2 x float> [[TMP9]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP11:%.*]] = fdiv <2 x float> [[TMP8]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x float> [[TMP11]], i64 1
; CHECK-NEXT:    ret float [[TMP12]]
;
entry:
  %0 = fadd float 0.000000e+00, 0.000000e+00
  %1 = fmul float 0.000000e+00, 0.000000e+00
  %2 = fmul float 0.000000e+00, %1
  %3 = fmul float 0.000000e+00, 0.000000e+00
  %4 = fadd float %3, 0.000000e+00
  %5 = fmul float %0, 0.000000e+00
  %6 = fmul float 0.000000e+00, %5
  %7 = fadd float %4, %6
  %8 = fadd float 0.000000e+00, %7
  %9 = fadd float %1, %5
  %10 = fadd float 0.000000e+00, %9
  %11 = fdiv float %8, %10
  %12 = fadd float 0.000000e+00, %2
  %13 = fmul float 0.000000e+00, %5
  %14 = fadd float %12, %13
  %15 = fadd float 0.000000e+00, %14
  %16 = fdiv float %15, %10
  ret float %16
}
