; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt %s -passes='print<scalar-evolution>' -disable-output \
; RUN:   -scalar-evolution-classify-expressions=0 2>&1 | FileCheck %s

; The latch compares the result of a sadd.with.overflow whose overflow bit
; exits the loop first. The result does not sign-wrap on any iteration that
; reaches the compare.

define void @sadd_guarded_sle(i64 %n) {
; CHECK-LABEL: 'sadd_guarded_sle'
; CHECK-NEXT:  Determining loop execution counts for: @sadd_guarded_sle
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:    exit count for loop: i64 288230376151711743
; CHECK-NEXT:    exit count for latch: ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i128 288230376151711743
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:    symbolic max exit count for loop: i64 288230376151711743
; CHECK-NEXT:    symbolic max exit count for latch: ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %latch ]
  %wo = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 32)
  %ov = extractvalue { i64, i1 } %wo, 1
  br i1 %ov, label %trap, label %latch

latch:
  %next = extractvalue { i64, i1 } %wo, 0
  %cmp = icmp sle i64 %next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void

trap:
  call void @llvm.trap()
  unreachable
}

; The compare executes before the overflow check.
define void @sadd_compare_before_check(i64 %n) {
; CHECK-LABEL: 'sadd_compare_before_check'
; CHECK-NEXT:  Determining loop execution counts for: @sadd_compare_before_check
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    predicated exit count for loop: ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:     Predicates:
; CHECK-NEXT:      {32,+,32}<nuw><%loop> Added Flags: <nssw>
; CHECK-EMPTY:
; CHECK-NEXT:    exit count for latch: i64 288230376151711743
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i64 288230376151711743
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is i64 288230376151711743
; CHECK-NEXT:    symbolic max exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    predicated symbolic max exit count for loop: ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:     Predicates:
; CHECK-NEXT:      {32,+,32}<nuw><%loop> Added Flags: <nssw>
; CHECK-EMPTY:
; CHECK-NEXT:    symbolic max exit count for latch: i64 288230376151711743
; CHECK-NEXT:  Loop %loop: Predicated backedge-taken count is ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:   Predicates:
; CHECK-NEXT:      {32,+,32}<nuw><%loop> Added Flags: <nssw>
; CHECK-NEXT:  Loop %loop: Predicated constant max backedge-taken count is i128 288230376151711743
; CHECK-NEXT:   Predicates:
; CHECK-NEXT:      {32,+,32}<nuw><%loop> Added Flags: <nssw>
; CHECK-NEXT:  Loop %loop: Predicated symbolic max backedge-taken count is ((-1 + (32 smax (1 + (sext i64 %n to i128))<nsw>))<nsw> /u 32)
; CHECK-NEXT:   Predicates:
; CHECK-NEXT:      {32,+,32}<nuw><%loop> Added Flags: <nssw>
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %latch ]
  %wo = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 32)
  %next = extractvalue { i64, i1 } %wo, 0
  %cmp = icmp sgt i64 %next, %n
  br i1 %cmp, label %exit, label %latch

latch:
  %ov = extractvalue { i64, i1 } %wo, 1
  br i1 %ov, label %trap, label %loop

exit:
  ret void

trap:
  call void @llvm.trap()
  unreachable
}

; The IV feeding the sadd.with.overflow may wrap: %iv.next = %iv + 64.
define void @sadd_iv_may_wrap(i64 %start, i64 %n) {
; CHECK-LABEL: 'sadd_iv_may_wrap'
; CHECK-NEXT:  Determining loop execution counts for: @sadd_iv_may_wrap
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    exit count for latch: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    predicated exit count for latch: ((63 + (-1 * (sext i64 (32 + %start) to i128))<nsw> + ((sext i64 (32 + %start) to i128) smax (1 + (sext i64 %n to i128))<nsw>)) /u 64)
; CHECK-NEXT:     Predicates:
; CHECK-NEXT:      {(32 + %start),+,64}<%loop> Added Flags: <nssw>
; CHECK-EMPTY:
; CHECK-NEXT:  Loop %loop: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable symbolic max backedge-taken count.
; CHECK-NEXT:    symbolic max exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    symbolic max exit count for latch: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    predicated symbolic max exit count for latch: ((63 + (-1 * (sext i64 (32 + %start) to i128))<nsw> + ((sext i64 (32 + %start) to i128) smax (1 + (sext i64 %n to i128))<nsw>)) /u 64)
; CHECK-NEXT:     Predicates:
; CHECK-NEXT:      {(32 + %start),+,64}<%loop> Added Flags: <nssw>
; CHECK-EMPTY:
; CHECK-NEXT:  Loop %loop: Predicated constant max backedge-taken count is i128 288230376151711744
; CHECK-NEXT:   Predicates:
; CHECK-NEXT:      {(32 + %start),+,64}<%loop> Added Flags: <nssw>
; CHECK-NEXT:  Loop %loop: Predicated symbolic max backedge-taken count is ((63 + (-1 * (sext i64 (32 + %start) to i128))<nsw> + ((sext i64 (32 + %start) to i128) smax (1 + (sext i64 %n to i128))<nsw>)) /u 64)
; CHECK-NEXT:   Predicates:
; CHECK-NEXT:      {(32 + %start),+,64}<%loop> Added Flags: <nssw>
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ %start, %entry ], [ %iv.next, %latch ]
  %wo = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 32)
  %ov = extractvalue { i64, i1 } %wo, 1
  br i1 %ov, label %trap, label %latch

latch:
  %next = extractvalue { i64, i1 } %wo, 0
  %iv.next = add i64 %iv, 64
  %cmp = icmp sle i64 %next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void

trap:
  call void @llvm.trap()
  unreachable
}

; An unsigned compare needs an unsigned no-wrap fact.
define void @sadd_guarded_ule(i64 %n) {
; CHECK-LABEL: 'sadd_guarded_ule'
; CHECK-NEXT:  Determining loop execution counts for: @sadd_guarded_ule
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: i64 288230376151711743
; CHECK-NEXT:    exit count for latch: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i64 288230376151711743
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is i64 288230376151711743
; CHECK-NEXT:    symbolic max exit count for loop: i64 288230376151711743
; CHECK-NEXT:    symbolic max exit count for latch: ***COULDNOTCOMPUTE***
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %latch ]
  %wo = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 32)
  %ov = extractvalue { i64, i1 } %wo, 1
  br i1 %ov, label %trap, label %latch

latch:
  %next = extractvalue { i64, i1 } %wo, 0
  %cmp = icmp ule i64 %next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void

trap:
  call void @llvm.trap()
  unreachable
}

declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare void @llvm.trap()
