; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt %s -passes='print<scalar-evolution>' -disable-output \
; RUN:   -scalar-evolution-classify-expressions=0 2>&1 | FileCheck %s

; The IV increments carry no wrap flags. A dominating guard on the bound
; keeps the IV from wrapping before the exit is taken.

define void @slt_guarded_rhs(i32 %n) {
; CHECK-LABEL: 'slt_guarded_rhs'
; CHECK-NEXT:  Determining loop execution counts for: @slt_guarded_rhs
; CHECK-NEXT:  Loop %loop: backedge-taken count is ((-1 + (4 smax %n))<nsw> /u 4)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 536870910
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (4 smax %n))<nsw> /u 4)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  %guard = icmp slt i32 %n, 1000
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i32 %iv, 4
  %cmp = icmp slt i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

define void @ult_guarded_rhs(i32 %n) {
; CHECK-LABEL: 'ult_guarded_rhs'
; CHECK-NEXT:  Determining loop execution counts for: @ult_guarded_rhs
; CHECK-NEXT:  Loop %loop: backedge-taken count is ((-1 + (4 umax %n)) /u 4)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 1073741822
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (4 umax %n)) /u 4)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  %guard = icmp ult i32 %n, 1000
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i32 %iv, 4
  %cmp = icmp ult i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; The guard leaves %n up to INT_MAX - 2, so the IV may wrap.
define void @slt_guarded_rhs_too_large(i32 %n) {
; CHECK-LABEL: 'slt_guarded_rhs_too_large'
; CHECK-NEXT:  Determining loop execution counts for: @slt_guarded_rhs_too_large
; CHECK-NEXT:  Loop %loop: Unpredictable backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable symbolic max backedge-taken count.
;
entry:
  %guard = icmp slt i32 %n, 2147483646
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i32 %iv, 4
  %cmp = icmp slt i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Multiple exits, as in a bounds-checked loop.
define void @slt_guarded_rhs_multiple_exits(i64 %n, i64 %len) {
; CHECK-LABEL: 'slt_guarded_rhs_multiple_exits'
; CHECK-NEXT:  Determining loop execution counts for: @slt_guarded_rhs_multiple_exits
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    exit count for latch: ((-1 + (4 smax %n))<nsw> /u 4)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i64 2305843009213693950
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (4 smax %n))<nsw> /u 4)
; CHECK-NEXT:    symbolic max exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    symbolic max exit count for latch: ((-1 + (4 smax %n))<nsw> /u 4)
;
entry:
  %guard = icmp slt i64 %n, 1000
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %iv.next = add i64 %iv, 4
  %oob = icmp ult i64 %len, %iv.next
  br i1 %oob, label %exit, label %latch

latch:
  %cmp = icmp slt i64 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}
