; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -disable-output "-passes=print<scalar-evolution>" -scalar-evolution-classify-expressions=0 < %s 2>&1 | FileCheck %s

; %n != 127 implies %n s<= 126, so iv.next = iv + 2 cannot wrap before
; iv.next s< %n fails.
define void @stride2_rhs_ne_smax(i8 %n) {
; CHECK-LABEL: 'stride2_rhs_ne_smax'
; CHECK-NEXT:  Determining loop execution counts for: @stride2_rhs_ne_smax
; CHECK-NEXT:  Loop %loop: backedge-taken count is ((-1 + (2 smax %n))<nsw> /u 2)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i8 62
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (2 smax %n))<nsw> /u 2)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  %is.max = icmp eq i8 %n, 127
  br i1 %is.max, label %exit, label %loop

loop:
  %iv = phi i8 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i8 %iv, 2
  %c = icmp slt i8 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Same as above with the guard on a switch default edge and an early exit.
define void @stride2_rhs_ne_smax_switch_multi_exit(ptr %p, i8 %n) {
; CHECK-LABEL: 'stride2_rhs_ne_smax_switch_multi_exit'
; CHECK-NEXT:  Determining loop execution counts for: @stride2_rhs_ne_smax_switch_multi_exit
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    exit count for latch: ((-1 + (2 smax %n))<nsw> /u 2)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i8 62
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (2 smax %n))<nsw> /u 2)
; CHECK-NEXT:    symbolic max exit count for loop: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    symbolic max exit count for latch: ((-1 + (2 smax %n))<nsw> /u 2)
;
entry:
  switch i8 %n, label %loop [
    i8 127, label %exit
    i8 0, label %exit
  ]

loop:
  %iv = phi i8 [ 0, %entry ], [ %iv.next, %latch ]
  %gep = getelementptr inbounds i8, ptr %p, i8 %iv
  %v = load i8, ptr %gep, align 1
  %done = icmp eq i8 %v, 0
  br i1 %done, label %exit, label %latch

latch:
  %iv.next = add i8 %iv, 2
  %c = icmp slt i8 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; %n != 127 allows %n == 126; with %start == 122, iv.next = 125 s< 126 and
; iv.next + 3 wraps.
define void @stride3_rhs_ne_smax(i8 %start, i8 %n) {
; CHECK-LABEL: 'stride3_rhs_ne_smax'
; CHECK-NEXT:  Determining loop execution counts for: @stride3_rhs_ne_smax
; CHECK-NEXT:  Loop %loop: Unpredictable backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable symbolic max backedge-taken count.
;
entry:
  %is.max = icmp eq i8 %n, 127
  br i1 %is.max, label %exit, label %loop

loop:
  %iv = phi i8 [ %start, %entry ], [ %iv.next, %loop ]
  %iv.next = add i8 %iv, 3
  %c = icmp slt i8 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; %n != -1 implies %n u<= 254, so iv.next = iv + 2 cannot wrap before
; iv.next u< %n fails.
define void @stride2_rhs_ne_umax(i8 %n) {
; CHECK-LABEL: 'stride2_rhs_ne_umax'
; CHECK-NEXT:  Determining loop execution counts for: @stride2_rhs_ne_umax
; CHECK-NEXT:  Loop %loop: backedge-taken count is ((-1 + (2 umax %n)) /u 2)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i8 126
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((-1 + (2 umax %n)) /u 2)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  %is.max = icmp eq i8 %n, -1
  br i1 %is.max, label %exit, label %loop

loop:
  %iv = phi i8 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i8 %iv, 2
  %c = icmp ult i8 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
