; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -disable-output "-passes=print<scalar-evolution>" -scalar-evolution-classify-expressions=0 < %s 2>&1 | FileCheck %s

; The switch default edge implies %n != 0, so the exit count is %n - 1.
define void @switch_default_ne_zero(i8 %n) {
; CHECK-LABEL: 'switch_default_ne_zero'
; CHECK-NEXT:  Determining loop execution counts for: @switch_default_ne_zero
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i8 -2
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  switch i8 %n, label %loop [
    i8 0, label %exit
  ]

loop:
  %iv = phi i8 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i8 %iv, 1
  %c = icmp ult i8 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; %n == 0 also reaches the loop through a case edge.
define void @switch_case_to_loop(i8 %n) {
; CHECK-LABEL: 'switch_case_to_loop'
; CHECK-NEXT:  Determining loop execution counts for: @switch_case_to_loop
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + (1 umax %n))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i8 -2
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + (1 umax %n))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  switch i8 %n, label %loop [
    i8 0, label %loop
    i8 1, label %exit
  ]

loop:
  %iv = phi i8 [ 0, %entry ], [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i8 %iv, 1
  %c = icmp ult i8 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
