; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S %s | FileCheck %s

; Unsigned midpoint: lo + ((hi - lo) >> 1) is at most hi, so the add does not
; wrap unsigned.
define i64 @midpoint_lshr(i64 %lo, i64 %hi) {
; CHECK-LABEL: define i64 @midpoint_lshr(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[M:%.*]] = add nuw i64 [[H]], [[LO]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, 1
  %m = add i64 %h, %lo
  ret i64 %m
}

define i64 @midpoint_lshr_commuted(i64 %lo, i64 %hi) {
; CHECK-LABEL: define i64 @midpoint_lshr_commuted(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[M:%.*]] = add nuw i64 [[LO]], [[H]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, 1
  %m = add i64 %lo, %h
  ret i64 %m
}

define i64 @midpoint_udiv(i64 %lo, i64 %hi, i64 %n) {
; CHECK-LABEL: define i64 @midpoint_udiv(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[Q:%.*]] = udiv i64 [[D]], [[N]]
; CHECK-NEXT:    [[M:%.*]] = add nuw i64 [[Q]], [[LO]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %q = udiv i64 %d, %n
  %m = add i64 %q, %lo
  ret i64 %m
}

define i64 @midpoint_lshr_var_amount(i64 %lo, i64 %hi, i64 %s) {
; CHECK-LABEL: define i64 @midpoint_lshr_var_amount(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]], i64 [[S:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], [[S]]
; CHECK-NEXT:    [[M:%.*]] = add nuw i64 [[H]], [[LO]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, %s
  %m = add i64 %h, %lo
  ret i64 %m
}

define <2 x i32> @midpoint_lshr_splat(<2 x i32> %lo, <2 x i32> %hi) {
; CHECK-LABEL: define <2 x i32> @midpoint_lshr_splat(
; CHECK-SAME: <2 x i32> [[LO:%.*]], <2 x i32> [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw <2 x i32> [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr <2 x i32> [[D]], splat (i32 1)
; CHECK-NEXT:    [[M:%.*]] = add nuw <2 x i32> [[H]], [[LO]]
; CHECK-NEXT:    ret <2 x i32> [[M]]
;
  %d = sub nuw <2 x i32> %hi, %lo
  %h = lshr <2 x i32> %d, splat (i32 1)
  %m = add <2 x i32> %h, %lo
  ret <2 x i32> %m
}

; Negative: sub without nuw may wrap.
define i64 @midpoint_sub_no_nuw(i64 %lo, i64 %hi) {
; CHECK-LABEL: define i64 @midpoint_sub_no_nuw(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[M:%.*]] = add i64 [[H]], [[LO]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub i64 %hi, %lo
  %h = lshr i64 %d, 1
  %m = add i64 %h, %lo
  ret i64 %m
}

; Negative: the add operand is the minuend, not the subtrahend.
define i64 @midpoint_add_minuend(i64 %lo, i64 %hi) {
; CHECK-LABEL: define i64 @midpoint_add_minuend(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[M:%.*]] = add i64 [[H]], [[HI]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, 1
  %m = add i64 %h, %hi
  ret i64 %m
}

; Negative: ashr is not bounded by its operand in the unsigned sense.
define i64 @midpoint_ashr(i64 %lo, i64 %hi) {
; CHECK-LABEL: define i64 @midpoint_ashr(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = ashr i64 [[D]], 1
; CHECK-NEXT:    [[M:%.*]] = add i64 [[H]], [[LO]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %h = ashr i64 %d, 1
  %m = add i64 %h, %lo
  ret i64 %m
}

; Negative: shl can exceed its operand.
define i64 @midpoint_shl(i64 %lo, i64 %hi) {
; CHECK-LABEL: define i64 @midpoint_shl(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = shl i64 [[D]], 1
; CHECK-NEXT:    [[M:%.*]] = add i64 [[H]], [[LO]]
; CHECK-NEXT:    ret i64 [[M]]
;
  %d = sub nuw i64 %hi, %lo
  %h = shl i64 %d, 1
  %m = add i64 %h, %lo
  ret i64 %m
}
