; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

; X u< Y with Y in [0, INT_MAX) implies X + 1 does not overflow signed.
define { i64, i1 } @sadd_dom_ult(i64 %x, ptr %p) {
; CHECK-LABEL: define { i64, i1 } @sadd_dom_ult(
; CHECK-SAME: i64 [[X:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[Y:%.*]] = load i64, ptr [[P]], align 4, !range [[RNG0:![0-9]+]]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[C]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[O:%.*]] = add nsw i64 [[X]], 1
; CHECK-NEXT:    [[TMP0:%.*]] = insertvalue { i64, i1 } { i64 poison, i1 false }, i64 [[O]], 0
; CHECK-NEXT:    ret { i64, i1 } [[TMP0]]
; CHECK:       [[F]]:
; CHECK-NEXT:    ret { i64, i1 } zeroinitializer
;
entry:
  %y = load i64, ptr %p, !range !0
  %c = icmp ult i64 %x, %y
  br i1 %c, label %t, label %f
t:
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %x, i64 1)
  ret { i64, i1 } %o
f:
  ret { i64, i1 } zeroinitializer
}

; X u< Y implies X + 1 does not overflow unsigned.
define { i8, i1 } @uadd_dom_ult(i8 %x, i8 %y) {
; CHECK-LABEL: define { i8, i1 } @uadd_dom_ult(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i8 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[C]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[O:%.*]] = add nuw i8 [[X]], 1
; CHECK-NEXT:    [[TMP0:%.*]] = insertvalue { i8, i1 } { i8 poison, i1 false }, i8 [[O]], 0
; CHECK-NEXT:    ret { i8, i1 } [[TMP0]]
; CHECK:       [[F]]:
; CHECK-NEXT:    ret { i8, i1 } zeroinitializer
;
entry:
  %c = icmp ult i8 %x, %y
  br i1 %c, label %t, label %f
t:
  %o = call { i8, i1 } @llvm.uadd.with.overflow.i8(i8 %x, i8 1)
  ret { i8, i1 } %o
f:
  ret { i8, i1 } zeroinitializer
}

; X s> Y implies X - 1 does not overflow signed.
define { i8, i1 } @ssub_dom_sgt(i8 %x, i8 %y) {
; CHECK-LABEL: define { i8, i1 } @ssub_dom_sgt(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i8 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[C]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[O:%.*]] = add nsw i8 [[X]], -1
; CHECK-NEXT:    [[TMP0:%.*]] = insertvalue { i8, i1 } { i8 poison, i1 false }, i8 [[O]], 0
; CHECK-NEXT:    ret { i8, i1 } [[TMP0]]
; CHECK:       [[F]]:
; CHECK-NEXT:    ret { i8, i1 } zeroinitializer
;
entry:
  %c = icmp sgt i8 %x, %y
  br i1 %c, label %t, label %f
t:
  %o = call { i8, i1 } @llvm.ssub.with.overflow.i8(i8 %x, i8 1)
  ret { i8, i1 } %o
f:
  ret { i8, i1 } zeroinitializer
}

; Negative test: X u< Y does not bound X below INT_MAX.
define { i8, i1 } @sadd_dom_ult_no_range(i8 %x, i8 %y) {
; CHECK-LABEL: define { i8, i1 } @sadd_dom_ult_no_range(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i8 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[C]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[O:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[X]], i8 1)
; CHECK-NEXT:    ret { i8, i1 } [[O]]
; CHECK:       [[F]]:
; CHECK-NEXT:    ret { i8, i1 } zeroinitializer
;
entry:
  %c = icmp ult i8 %x, %y
  br i1 %c, label %t, label %f
t:
  %o = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %x, i8 1)
  ret { i8, i1 } %o
f:
  ret { i8, i1 } zeroinitializer
}

; Negative test: the condition holds on the other edge.
define { i8, i1 } @uadd_dom_ult_false_edge(i8 %x, i8 %y) {
; CHECK-LABEL: define { i8, i1 } @uadd_dom_ult_false_edge(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i8 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[C]], label %[[F:.*]], label %[[T:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[O:%.*]] = call { i8, i1 } @llvm.uadd.with.overflow.i8(i8 [[X]], i8 1)
; CHECK-NEXT:    ret { i8, i1 } [[O]]
; CHECK:       [[F]]:
; CHECK-NEXT:    ret { i8, i1 } zeroinitializer
;
entry:
  %c = icmp ult i8 %x, %y
  br i1 %c, label %f, label %t
t:
  %o = call { i8, i1 } @llvm.uadd.with.overflow.i8(i8 %x, i8 1)
  ret { i8, i1 } %o
f:
  ret { i8, i1 } zeroinitializer
}

!0 = !{i64 0, i64 9223372036854775807}
;.
; CHECK: [[RNG0]] = !{i64 0, i64 9223372036854775807}
;.
