; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @llvm.assume(i1)

; An add without flags of non-negative operands does not wrap unsigned.
define i1 @add_nonneg_ops_uge(i8 %a, i8 %b) {
; CHECK-LABEL: @add_nonneg_ops_uge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[A]], [[B]]
; CHECK-NEXT:    ret i1 true
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %add = add i8 %a, %b
  %c = icmp uge i8 %add, %a
  ret i1 %c
}

define i1 @add_maybe_neg_op_uge(i8 %a, i8 %b) {
; CHECK-LABEL: @add_maybe_neg_op_uge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[A]], [[B:%.*]]
; CHECK-NEXT:    [[C:%.*]] = icmp uge i8 [[ADD]], [[A]]
; CHECK-NEXT:    ret i1 [[C]]
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %add = add i8 %a, %b
  %c = icmp uge i8 %add, %a
  ret i1 %c
}

; base + n <=u n with base, n >=s 0 implies base == 0.
define i1 @add_nonneg_ops_ule_implies_zero(i8 %base, i8 %n) {
; CHECK-LABEL: @add_nonneg_ops_ule_implies_zero(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[N_NONNEG:%.*]] = icmp sge i8 [[N:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[N_NONNEG]])
; CHECK-NEXT:    [[BASE_ULE:%.*]] = icmp ule i8 [[BASE:%.*]], [[N]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[BASE_ULE]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[BASE]], [[N]]
; CHECK-NEXT:    [[ADD_ULE:%.*]] = icmp ule i8 [[ADD]], [[N]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[ADD_ULE]])
; CHECK-NEXT:    ret i1 true
;
entry:
  %n.nonneg = icmp sge i8 %n, 0
  call void @llvm.assume(i1 %n.nonneg)
  %base.ule = icmp ule i8 %base, %n
  call void @llvm.assume(i1 %base.ule)
  %add = add i8 %base, %n
  %add.ule = icmp ule i8 %add, %n
  call void @llvm.assume(i1 %add.ule)
  %c = icmp ule i8 %base, 0
  ret i1 %c
}

; With a non-negative result, the add does not wrap signed either.
define i1 @add_nonneg_ops_nonneg_result_sge(i8 %a, i8 %b) {
; CHECK-LABEL: @add_nonneg_ops_nonneg_result_sge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[A]], [[B]]
; CHECK-NEXT:    [[ADD_NONNEG:%.*]] = icmp sge i8 [[ADD]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[ADD_NONNEG]])
; CHECK-NEXT:    ret i1 true
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %add = add i8 %a, %b
  %add.nonneg = icmp sge i8 %add, 0
  call void @llvm.assume(i1 %add.nonneg)
  %c = icmp sge i8 %add, %a
  ret i1 %c
}

define i1 @add_nonneg_ops_maybe_neg_result_sge(i8 %a, i8 %b) {
; CHECK-LABEL: @add_nonneg_ops_maybe_neg_result_sge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp sge i8 [[ADD]], [[A]]
; CHECK-NEXT:    ret i1 [[C]]
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %add = add i8 %a, %b
  %c = icmp sge i8 %add, %a
  ret i1 %c
}

define i1 @add_maybe_neg_op_nonneg_result_sge(i8 %a, i8 %b) {
; CHECK-LABEL: @add_maybe_neg_op_nonneg_result_sge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[A]], [[B:%.*]]
; CHECK-NEXT:    [[ADD_NONNEG:%.*]] = icmp sge i8 [[ADD]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[ADD_NONNEG]])
; CHECK-NEXT:    [[C:%.*]] = icmp sge i8 [[ADD]], [[A]]
; CHECK-NEXT:    ret i1 [[C]]
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %add = add i8 %a, %b
  %add.nonneg = icmp sge i8 %add, 0
  call void @llvm.assume(i1 %add.nonneg)
  %c = icmp sge i8 %add, %a
  ret i1 %c
}

; The fact on %base is added before the fact on %add, so %base >=s 0 is
; known when decomposing %add.
define i1 @or_fact_on_add_after_fact_on_operand(i8 %base, i8 %n) {
; CHECK-LABEL: @or_fact_on_add_after_fact_on_operand(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[N_NONNEG:%.*]] = icmp sge i8 [[N:%.*]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[N_NONNEG]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[BASE:%.*]], [[N]]
; CHECK-NEXT:    [[C_ADD:%.*]] = icmp ult i8 [[N]], [[ADD]]
; CHECK-NEXT:    [[C_BASE:%.*]] = icmp ult i8 [[N]], [[BASE]]
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[C_ADD]], [[C_BASE]]
; CHECK-NEXT:    br i1 [[OR]], label [[EXIT:%.*]], label [[THEN:%.*]]
; CHECK:       then:
; CHECK-NEXT:    ret i1 true
; CHECK:       exit:
; CHECK-NEXT:    ret i1 false
;
entry:
  %n.nonneg = icmp sge i8 %n, 0
  call void @llvm.assume(i1 %n.nonneg)
  %add = add i8 %base, %n
  %c.add = icmp ult i8 %n, %add
  %c.base = icmp ult i8 %n, %base
  %or = or i1 %c.add, %c.base
  br i1 %or, label %exit, label %then

then:
  %c = icmp ule i8 %base, 0
  ret i1 %c

exit:
  ret i1 false
}
