; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @llvm.assume(i1)

; q <=u z - y and z >=u y, so q + y <=u z does not wrap and the compare is
; true.
define i1 @add_of_udiv_of_sub(i64 %z, i64 %y, i64 %n) {
; CHECK-LABEL: define i1 @add_of_udiv_of_sub(
; CHECK-SAME: i64 [[Z:%.*]], i64 [[Y:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[GE:%.*]] = icmp uge i64 [[Z]], [[Y]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[GE]])
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[Z]], [[Y]]
; CHECK-NEXT:    [[Q:%.*]] = udiv i64 [[D]], [[N]]
; CHECK-NEXT:    [[A:%.*]] = add nuw i64 [[Q]], [[Y]]
; CHECK-NEXT:    ret i1 true
;
  %ge = icmp uge i64 %z, %y
  call void @llvm.assume(i1 %ge)
  %d = sub i64 %z, %y
  %q = udiv i64 %d, %n
  %a = add i64 %q, %y
  %c = icmp ule i64 %a, %z
  ret i1 %c
}

define i1 @add_of_lshr_of_sub_commuted(i64 %z, i64 %y) {
; CHECK-LABEL: define i1 @add_of_lshr_of_sub_commuted(
; CHECK-SAME: i64 [[Z:%.*]], i64 [[Y:%.*]]) {
; CHECK-NEXT:    [[GE:%.*]] = icmp uge i64 [[Z]], [[Y]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[GE]])
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[Z]], [[Y]]
; CHECK-NEXT:    [[Q:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[A:%.*]] = add nuw i64 [[Y]], [[Q]]
; CHECK-NEXT:    ret i1 true
;
  %ge = icmp uge i64 %z, %y
  call void @llvm.assume(i1 %ge)
  %d = sub i64 %z, %y
  %q = lshr i64 %d, 1
  %a = add i64 %y, %q
  %c = icmp ule i64 %a, %z
  ret i1 %c
}

; Negative: z >=u y is not known, so z - y may wrap.
define i1 @add_of_udiv_of_sub_no_order(i64 %z, i64 %y, i64 %n) {
; CHECK-LABEL: define i1 @add_of_udiv_of_sub_no_order(
; CHECK-SAME: i64 [[Z:%.*]], i64 [[Y:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[Z]], [[Y]]
; CHECK-NEXT:    [[Q:%.*]] = udiv i64 [[D]], [[N]]
; CHECK-NEXT:    [[A:%.*]] = add i64 [[Q]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp ule i64 [[A]], [[Z]]
; CHECK-NEXT:    ret i1 [[C]]
;
  %d = sub i64 %z, %y
  %q = udiv i64 %d, %n
  %a = add i64 %q, %y
  %c = icmp ule i64 %a, %z
  ret i1 %c
}

; Negative: the sub's subtrahend is not the other add operand.
define i1 @add_of_udiv_of_sub_other_operand(i64 %z, i64 %y, i64 %x, i64 %n) {
; CHECK-LABEL: define i1 @add_of_udiv_of_sub_other_operand(
; CHECK-SAME: i64 [[Z:%.*]], i64 [[Y:%.*]], i64 [[X:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[GE:%.*]] = icmp uge i64 [[Z]], [[Y]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[GE]])
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[Z]], [[Y]]
; CHECK-NEXT:    [[Q:%.*]] = udiv i64 [[D]], [[N]]
; CHECK-NEXT:    [[A:%.*]] = add i64 [[Q]], [[X]]
; CHECK-NEXT:    [[C:%.*]] = icmp ule i64 [[A]], [[Z]]
; CHECK-NEXT:    ret i1 [[C]]
;
  %ge = icmp uge i64 %z, %y
  call void @llvm.assume(i1 %ge)
  %d = sub i64 %z, %y
  %q = udiv i64 %d, %n
  %a = add i64 %q, %x
  %c = icmp ule i64 %a, %z
  ret i1 %c
}
