; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)
declare i1 @cond(i64)

; Rotated binary search over [0, n): mid = lo + (hi - lo) / 2,
; hi.next = select(c, hi, mid), lo.next = select(c, mid + 1, lo), and the
; latch branches back on lo.next <s hi.next. 0 <= lo <s hi <= n holds in the
; header, so mid <u n.
define void @binary_search_sdiv(i64 %n) {
; CHECK-LABEL: define void @binary_search_sdiv(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[Q:%.*]] = sdiv i64 [[D]], 2
; CHECK-NEXT:    [[MID:%.*]] = add i64 [[Q]], [[LO]]
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[MID]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[IN_BOUNDS]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[MID]])
; CHECK-NEXT:    [[MID_1:%.*]] = add i64 [[MID]], 1
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[HI]], i64 [[MID]]
; CHECK-NEXT:    [[LO_NEXT]] = select i1 [[C]], i64 [[MID_1]], i64 [[LO]]
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[LO_NEXT]], [[HI_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %lo = phi i64 [ 0, %entry ], [ %lo.next, %loop ]
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %lo.nonneg = icmp sge i64 %lo, 0
  call void @use(i1 %lo.nonneg)
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %d = sub i64 %hi, %lo
  %q = sdiv i64 %d, 2
  %mid = add i64 %q, %lo
  %in.bounds = icmp ult i64 %mid, %n
  call void @use(i1 %in.bounds)
  %c = call i1 @cond(i64 %mid)
  %mid.1 = add i64 %mid, 1
  %hi.next = select i1 %c, i64 %hi, i64 %mid
  %lo.next = select i1 %c, i64 %mid.1, i64 %lo
  %cont = icmp slt i64 %lo.next, %hi.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; Same with lshr by 1.
define void @binary_search_lshr(i64 %n) {
; CHECK-LABEL: define void @binary_search_lshr(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[Q:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[MID:%.*]] = add i64 [[LO]], [[Q]]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[MID]])
; CHECK-NEXT:    [[MID_1:%.*]] = add i64 [[MID]], 1
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[MID]], i64 [[HI]]
; CHECK-NEXT:    [[LO_NEXT]] = select i1 [[C]], i64 [[LO]], i64 [[MID_1]]
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[LO_NEXT]], [[HI_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %lo = phi i64 [ 0, %entry ], [ %lo.next, %loop ]
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %d = sub i64 %hi, %lo
  %q = lshr i64 %d, 1
  %mid = add i64 %lo, %q
  %c = call i1 @cond(i64 %mid)
  %mid.1 = add i64 %mid, 1
  %hi.next = select i1 %c, i64 %mid, i64 %hi
  %lo.next = select i1 %c, i64 %lo, i64 %mid.1
  %cont = icmp slt i64 %lo.next, %hi.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; Negative: dividing by 1 gives mid = hi.
define void @binary_search_sdiv_by_one(i64 %n) {
; CHECK-LABEL: define void @binary_search_sdiv_by_one(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[Q:%.*]] = sdiv i64 [[D]], 1
; CHECK-NEXT:    [[MID:%.*]] = add i64 [[Q]], [[LO]]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[MID]])
; CHECK-NEXT:    [[MID_1:%.*]] = add i64 [[MID]], 1
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[HI]], i64 [[MID]]
; CHECK-NEXT:    [[LO_NEXT]] = select i1 [[C]], i64 [[MID_1]], i64 [[LO]]
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[LO_NEXT]], [[HI_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %lo = phi i64 [ 0, %entry ], [ %lo.next, %loop ]
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %d = sub i64 %hi, %lo
  %q = sdiv i64 %d, 1
  %mid = add i64 %q, %lo
  %c = call i1 @cond(i64 %mid)
  %mid.1 = add i64 %mid, 1
  %hi.next = select i1 %c, i64 %hi, i64 %mid
  %lo.next = select i1 %c, i64 %mid.1, i64 %lo
  %cont = icmp slt i64 %lo.next, %hi.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; Negative: a negative start for lo allows hi - lo to wrap.
define void @binary_search_negative_lo_start(i64 %n) {
; CHECK-LABEL: define void @binary_search_negative_lo_start(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], -1
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i64 [ -1, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[Q:%.*]] = sdiv i64 [[D]], 2
; CHECK-NEXT:    [[MID:%.*]] = add i64 [[Q]], [[LO]]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[MID]])
; CHECK-NEXT:    [[MID_1:%.*]] = add i64 [[MID]], 1
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[HI]], i64 [[MID]]
; CHECK-NEXT:    [[LO_NEXT]] = select i1 [[C]], i64 [[MID_1]], i64 [[LO]]
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[LO_NEXT]], [[HI_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, -1
  br i1 %pos, label %loop, label %exit

loop:
  %lo = phi i64 [ -1, %entry ], [ %lo.next, %loop ]
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %d = sub i64 %hi, %lo
  %q = sdiv i64 %d, 2
  %mid = add i64 %q, %lo
  %c = call i1 @cond(i64 %mid)
  %mid.1 = add i64 %mid, 1
  %hi.next = select i1 %c, i64 %hi, i64 %mid
  %lo.next = select i1 %c, i64 %mid.1, i64 %lo
  %cont = icmp slt i64 %lo.next, %hi.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; Negative: lo steps to mid + 2.
define void @binary_search_lo_step_two(i64 %n) {
; CHECK-LABEL: define void @binary_search_lo_step_two(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[D:%.*]] = sub i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[Q:%.*]] = sdiv i64 [[D]], 2
; CHECK-NEXT:    [[MID:%.*]] = add i64 [[Q]], [[LO]]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[MID]])
; CHECK-NEXT:    [[MID_2:%.*]] = add i64 [[MID]], 2
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[HI]], i64 [[MID]]
; CHECK-NEXT:    [[LO_NEXT]] = select i1 [[C]], i64 [[MID_2]], i64 [[LO]]
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[LO_NEXT]], [[HI_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %lo = phi i64 [ 0, %entry ], [ %lo.next, %loop ]
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %d = sub i64 %hi, %lo
  %q = sdiv i64 %d, 2
  %mid = add i64 %q, %lo
  %c = call i1 @cond(i64 %mid)
  %mid.2 = add i64 %mid, 2
  %hi.next = select i1 %c, i64 %hi, i64 %mid
  %lo.next = select i1 %c, i64 %mid.2, i64 %lo
  %cont = icmp slt i64 %lo.next, %hi.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}
