; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; Search over a halving range: s.next = select(c, s + r, s),
; r.next = (r >> 1) & ~1, s.start = 0, r.start = (n >> 1) & ~1. Then
; s + 2 * r <= n in the header, and with r u> 2, s + r u< n.
define i64 @halving_search(ptr %a, i64 %n, i32 %t) {
; CHECK-LABEL: define i64 @halving_search(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]], i32 [[T:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[H0:%.*]] = lshr i64 [[N]], 1
; CHECK-NEXT:    [[R0:%.*]] = and i64 [[H0]], -2
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[R0]], 2
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT:%.*]], %[[BODY:.*]] ]
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[R0]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[R]], [[S]]
; CHECK-NEXT:    br i1 true, label %[[BODY]], label %[[TRAP:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[SUM]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[LT:%.*]] = icmp slt i32 [[V]], [[T]]
; CHECK-NEXT:    [[S_NEXT]] = select i1 [[LT]], i64 [[SUM]], i64 [[S]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[R_NEXT]] = and i64 [[H]], -2
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 2
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT]], %[[BODY]] ]
; CHECK-NEXT:    ret i64 [[RES]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %h0 = lshr i64 %n, 1
  %r0 = and i64 %h0, -2
  %pre = icmp ugt i64 %r0, 2
  br i1 %pre, label %loop, label %exit

loop:
  %s = phi i64 [ 0, %entry ], [ %s.next, %body ]
  %r = phi i64 [ %r0, %entry ], [ %r.next, %body ]
  %sum = add i64 %r, %s
  %in.bounds = icmp ult i64 %sum, %n
  br i1 %in.bounds, label %body, label %trap

body:
  %gep = getelementptr inbounds i32, ptr %a, i64 %sum
  %v = load i32, ptr %gep, align 4
  %lt = icmp slt i32 %v, %t
  %s.next = select i1 %lt, i64 %sum, i64 %s
  %h = lshr i64 %r, 1
  %r.next = and i64 %h, -2
  %ec = icmp ugt i64 %r.next, 2
  br i1 %ec, label %loop, label %exit

exit:
  %res = phi i64 [ 0, %entry ], [ %s.next, %body ]
  ret i64 %res

trap:
  call void @llvm.trap()
  unreachable
}

; s always steps to s + r.
define void @halving_search_add(ptr %a, i64 %n) {
; CHECK-LABEL: define void @halving_search_add(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[R0:%.*]] = lshr i64 [[N]], 2
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[R0]], 0
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[SUM:%.*]], %[[BODY:.*]] ]
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[R0]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    [[SUM]] = add i64 [[S]], [[R]]
; CHECK-NEXT:    br i1 true, label %[[BODY]], label %[[TRAP:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[R_NEXT]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 0
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %r0 = lshr i64 %n, 2
  %pre = icmp ugt i64 %r0, 0
  br i1 %pre, label %loop, label %exit

loop:
  %s = phi i64 [ 0, %entry ], [ %sum, %body ]
  %r = phi i64 [ %r0, %entry ], [ %r.next, %body ]
  %sum = add i64 %s, %r
  %in.bounds = icmp ult i64 %sum, %n
  br i1 %in.bounds, label %body, label %trap

body:
  %r.next = lshr i64 %r, 1
  %ec = icmp ugt i64 %r.next, 0
  br i1 %ec, label %loop, label %exit

exit:
  ret void

trap:
  call void @llvm.trap()
  unreachable
}

; r.start = n / 2 + 1: s + 2 * r <= n does not hold for the start values.
define i64 @halving_search_start_too_large(ptr %a, i64 %n, i32 %t) {
; CHECK-LABEL: define i64 @halving_search_start_too_large(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]], i32 [[T:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[H0:%.*]] = lshr i64 [[N]], 1
; CHECK-NEXT:    [[R0:%.*]] = add nuw i64 [[H0]], 1
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[R0]], 2
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT:%.*]], %[[BODY:.*]] ]
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[R0]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[R]], [[S]]
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[SUM]], [[N]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label %[[BODY]], label %[[TRAP:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[SUM]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[LT:%.*]] = icmp slt i32 [[V]], [[T]]
; CHECK-NEXT:    [[S_NEXT]] = select i1 [[LT]], i64 [[SUM]], i64 [[S]]
; CHECK-NEXT:    [[R_NEXT]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 2
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT]], %[[BODY]] ]
; CHECK-NEXT:    ret i64 [[RES]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %h0 = lshr i64 %n, 1
  %r0 = add nuw i64 %h0, 1
  %pre = icmp ugt i64 %r0, 2
  br i1 %pre, label %loop, label %exit

loop:
  %s = phi i64 [ 0, %entry ], [ %s.next, %body ]
  %r = phi i64 [ %r0, %entry ], [ %r.next, %body ]
  %sum = add i64 %r, %s
  %in.bounds = icmp ult i64 %sum, %n
  br i1 %in.bounds, label %body, label %trap

body:
  %gep = getelementptr inbounds i32, ptr %a, i64 %sum
  %v = load i32, ptr %gep, align 4
  %lt = icmp slt i32 %v, %t
  %s.next = select i1 %lt, i64 %sum, i64 %s
  %r.next = lshr i64 %r, 1
  %ec = icmp ugt i64 %r.next, 2
  br i1 %ec, label %loop, label %exit

exit:
  %res = phi i64 [ 0, %entry ], [ %s.next, %body ]
  ret i64 %res

trap:
  call void @llvm.trap()
  unreachable
}

; s steps to s + r + 1, which can exceed s + 2 * r.next + r.
define i64 @halving_search_step_plus_one(ptr %a, i64 %n, i32 %t) {
; CHECK-LABEL: define i64 @halving_search_step_plus_one(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]], i32 [[T:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[H0:%.*]] = lshr i64 [[N]], 1
; CHECK-NEXT:    [[R0:%.*]] = and i64 [[H0]], -2
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[R0]], 2
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT:%.*]], %[[BODY:.*]] ]
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[R0]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[R]], [[S]]
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[SUM]], [[N]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label %[[BODY]], label %[[TRAP:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[SUM]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[LT:%.*]] = icmp slt i32 [[V]], [[T]]
; CHECK-NEXT:    [[SUM1:%.*]] = add i64 [[SUM]], 1
; CHECK-NEXT:    [[S_NEXT]] = select i1 [[LT]], i64 [[SUM1]], i64 [[S]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[R_NEXT]] = and i64 [[H]], -2
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 2
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT]], %[[BODY]] ]
; CHECK-NEXT:    ret i64 [[RES]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %h0 = lshr i64 %n, 1
  %r0 = and i64 %h0, -2
  %pre = icmp ugt i64 %r0, 2
  br i1 %pre, label %loop, label %exit

loop:
  %s = phi i64 [ 0, %entry ], [ %s.next, %body ]
  %r = phi i64 [ %r0, %entry ], [ %r.next, %body ]
  %sum = add i64 %r, %s
  %in.bounds = icmp ult i64 %sum, %n
  br i1 %in.bounds, label %body, label %trap

body:
  %gep = getelementptr inbounds i32, ptr %a, i64 %sum
  %v = load i32, ptr %gep, align 4
  %lt = icmp slt i32 %v, %t
  %sum1 = add i64 %sum, 1
  %s.next = select i1 %lt, i64 %sum1, i64 %s
  %h = lshr i64 %r, 1
  %r.next = and i64 %h, -2
  %ec = icmp ugt i64 %r.next, 2
  br i1 %ec, label %loop, label %exit

exit:
  %res = phi i64 [ 0, %entry ], [ %s.next, %body ]
  ret i64 %res

trap:
  call void @llvm.trap()
  unreachable
}

; r does not shrink: r.next = r.
define i64 @halving_search_no_halving(ptr %a, i64 %n, i32 %t) {
; CHECK-LABEL: define i64 @halving_search_no_halving(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]], i32 [[T:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[H0:%.*]] = lshr i64 [[N]], 1
; CHECK-NEXT:    [[R0:%.*]] = and i64 [[H0]], -2
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[R0]], 2
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT:%.*]], %[[BODY:.*]] ]
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[R0]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[R]], [[S]]
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[SUM]], [[N]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label %[[BODY]], label %[[TRAP:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[SUM]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[LT:%.*]] = icmp slt i32 [[V]], [[T]]
; CHECK-NEXT:    [[S_NEXT]] = select i1 [[LT]], i64 [[SUM]], i64 [[S]]
; CHECK-NEXT:    [[R_NEXT]] = and i64 [[R]], -2
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 2
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[S_NEXT]], %[[BODY]] ]
; CHECK-NEXT:    ret i64 [[RES]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %h0 = lshr i64 %n, 1
  %r0 = and i64 %h0, -2
  %pre = icmp ugt i64 %r0, 2
  br i1 %pre, label %loop, label %exit

loop:
  %s = phi i64 [ 0, %entry ], [ %s.next, %body ]
  %r = phi i64 [ %r0, %entry ], [ %r.next, %body ]
  %sum = add i64 %r, %s
  %in.bounds = icmp ult i64 %sum, %n
  br i1 %in.bounds, label %body, label %trap

body:
  %gep = getelementptr inbounds i32, ptr %a, i64 %sum
  %v = load i32, ptr %gep, align 4
  %lt = icmp slt i32 %v, %t
  %s.next = select i1 %lt, i64 %sum, i64 %s
  %r.next = and i64 %r, -2
  %ec = icmp ugt i64 %r.next, 2
  br i1 %ec, label %loop, label %exit

exit:
  %res = phi i64 [ 0, %entry ], [ %s.next, %body ]
  ret i64 %res

trap:
  call void @llvm.trap()
  unreachable
}
