; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)

; Both backedges carry %iv.next, so %iv is a single induction.
define void @same_backedge_value(i64 %n, i1 %c) {
; CHECK-LABEL: define void @same_backedge_value(
; CHECK-SAME: i64 [[N:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH_A:.*]] ], [ [[IV_NEXT]], %[[LATCH_B:.*]] ]
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 1
; CHECK-NEXT:    br i1 [[C]], label %[[LATCH_A]], label %[[LATCH_B]]
; CHECK:       [[LATCH_A]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[LATCH_B]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  br i1 %pre, label %loop, label %exit

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch.a ], [ %iv.next, %latch.b ]
  %ec = icmp eq i64 %iv, %n
  br i1 %ec, label %exit, label %body

body:
  %t.1 = icmp slt i64 %iv, %n
  call void @use(i1 %t.1)
  %t.2 = icmp ult i64 %iv, %n
  call void @use(i1 %t.2)
  %iv.next = add i64 %iv, 1
  br i1 %c, label %latch.a, label %latch.b

latch.a:
  br label %loop

latch.b:
  br label %loop

exit:
  ret void
}

; The backedges carry different values; no induction facts.
define void @different_backedge_values(i64 %n, i1 %c) {
; CHECK-LABEL: define void @different_backedge_values(
; CHECK-SAME: i64 [[N:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH_A:.*]] ], [ [[IV_NEXT_2:%.*]], %[[LATCH_B:.*]] ]
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[C_1:%.*]] = icmp slt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C_1]])
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[IV_NEXT_2]] = add i64 [[IV]], 2
; CHECK-NEXT:    br i1 [[C]], label %[[LATCH_A]], label %[[LATCH_B]]
; CHECK:       [[LATCH_A]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[LATCH_B]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  br i1 %pre, label %loop, label %exit

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch.a ], [ %iv.next.2, %latch.b ]
  %ec = icmp eq i64 %iv, %n
  br i1 %ec, label %exit, label %body

body:
  %c.1 = icmp slt i64 %iv, %n
  call void @use(i1 %c.1)
  %iv.next = add i64 %iv, 1
  %iv.next.2 = add i64 %iv, 2
  br i1 %c, label %latch.a, label %latch.b

latch.a:
  br label %loop

latch.b:
  br label %loop

exit:
  ret void
}
