; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)
declare i64 @next(i64)

; The latch branches back only if i.next <s j.next, and 0 <s n holds on
; entry, so i <s j holds in the header.
define void @latch_slt(i64 %n) {
; CHECK-LABEL: define void @latch_slt(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[J_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[I_NEXT]] = call i64 @next(i64 [[I]])
; CHECK-NEXT:    [[J_NEXT]] = call i64 @next(i64 [[J]])
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[I_NEXT]], [[J_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i64 [ %n, %entry ], [ %j.next, %loop ]
  %c = icmp slt i64 %i, %j
  call void @use(i1 %c)
  %i.next = call i64 @next(i64 %i)
  %j.next = call i64 @next(i64 %j)
  %cont = icmp slt i64 %i.next, %j.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; The latch branches back on the false edge of i.next >=u j.next.
define void @latch_uge_false_edge(i64 %n) {
; CHECK-LABEL: define void @latch_uge_false_edge(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[J_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[I_NEXT]] = call i64 @next(i64 [[I]])
; CHECK-NEXT:    [[J_NEXT]] = call i64 @next(i64 [[J]])
; CHECK-NEXT:    [[DONE:%.*]] = icmp uge i64 [[I_NEXT]], [[J_NEXT]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp ne i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i64 [ %n, %entry ], [ %j.next, %loop ]
  %c = icmp ult i64 %i, %j
  call void @use(i1 %c)
  %i.next = call i64 @next(i64 %i)
  %j.next = call i64 @next(i64 %j)
  %done = icmp uge i64 %i.next, %j.next
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: the compare does not hold for the start values.
define void @latch_slt_start_not_known(i64 %n) {
; CHECK-LABEL: define void @latch_slt_start_not_known(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[J_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[I]], [[J]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    [[I_NEXT]] = call i64 @next(i64 [[I]])
; CHECK-NEXT:    [[J_NEXT]] = call i64 @next(i64 [[J]])
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[I_NEXT]], [[J_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i64 [ %n, %entry ], [ %j.next, %loop ]
  %c = icmp slt i64 %i, %j
  call void @use(i1 %c)
  %i.next = call i64 @next(i64 %i)
  %j.next = call i64 @next(i64 %j)
  %cont = icmp slt i64 %i.next, %j.next
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; Negative: the latch compares a value that is not a phi's backedge value.
define void @latch_cmp_not_backedge_value(i64 %n) {
; CHECK-LABEL: define void @latch_cmp_not_backedge_value(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[POS:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[POS]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[J_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[I]], [[J]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    [[I_NEXT]] = call i64 @next(i64 [[I]])
; CHECK-NEXT:    [[J_NEXT]] = call i64 @next(i64 [[J]])
; CHECK-NEXT:    [[K:%.*]] = call i64 @next(i64 [[J_NEXT]])
; CHECK-NEXT:    [[CONT:%.*]] = icmp slt i64 [[I_NEXT]], [[K]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pos = icmp sgt i64 %n, 0
  br i1 %pos, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i64 [ %n, %entry ], [ %j.next, %loop ]
  %c = icmp slt i64 %i, %j
  call void @use(i1 %c)
  %i.next = call i64 @next(i64 %i)
  %j.next = call i64 @next(i64 %j)
  %k = call i64 @next(i64 %j.next)
  %cont = icmp slt i64 %i.next, %k
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; Negative: samesign on the latch compare only holds on the backedge, so the
; signed compare on entry (lo = 1, hi = -1) is not implied by ult on the starts.
define i1 @latch_samesign_ult(i1 %d) {
; CHECK-LABEL: define i1 @latch_samesign_ult(
; CHECK-SAME: i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i8 [ 1, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i8 [ -1, %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i8 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[D]], label %[[LATCH]], label %[[EXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[LO_NEXT]] = add i8 [[LO]], 1
; CHECK-NEXT:    [[HI_NEXT]] = add i8 [[HI]], 0
; CHECK-NEXT:    [[CONT:%.*]] = icmp samesign ult i8 [[LO_NEXT]], [[HI_NEXT]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 [[C]]
;
entry:
  br label %loop

loop:
  %lo = phi i8 [ 1, %entry ], [ %lo.next, %latch ]
  %hi = phi i8 [ -1, %entry ], [ %hi.next, %latch ]
  %c = icmp slt i8 %lo, %hi
  br i1 %d, label %latch, label %exit

latch:
  %lo.next = add i8 %lo, 1
  %hi.next = add i8 %hi, 0
  %cont = icmp samesign ult i8 %lo.next, %hi.next
  br i1 %cont, label %loop, label %exit

exit:
  ret i1 %c
}
