; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)

; The latch continues if r.next u> 2, and r.start u> 2, so r u> 2 in the
; header. r.next is not an add recurrence.
define void @latch_invariant_bound(i64 %start) {
; CHECK-LABEL: define void @latch_invariant_bound(
; CHECK-SAME: i64 [[START:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[START]], 2
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[R_NEXT]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 2
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ugt i64 %start, 2
  br i1 %pre, label %loop, label %exit

loop:
  %r = phi i64 [ %start, %entry ], [ %r.next, %loop ]
  %c = icmp ugt i64 %r, 2
  call void @use(i1 %c)
  %r.next = lshr i64 %r, 1
  %ec = icmp ugt i64 %r.next, 2
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; The start value is not known to satisfy the latch condition.
define void @latch_invariant_bound_no_start(i64 %start) {
; CHECK-LABEL: define void @latch_invariant_bound_no_start(
; CHECK-SAME: i64 [[START:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i64 [[R]], 2
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    [[R_NEXT]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], 2
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %r = phi i64 [ %start, %entry ], [ %r.next, %loop ]
  %c = icmp ugt i64 %r, 2
  call void @use(i1 %c)
  %r.next = lshr i64 %r, 1
  %ec = icmp ugt i64 %r.next, 2
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; The bound is not loop-invariant.
define void @latch_variant_bound(i64 %start, ptr %p) {
; CHECK-LABEL: define void @latch_variant_bound(
; CHECK-SAME: i64 [[START:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[START]], 2
; CHECK-NEXT:    br i1 [[PRE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[R_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[B:%.*]] = load i64, ptr [[P]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i64 [[R]], 2
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    [[R_NEXT]] = lshr i64 [[R]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ugt i64 [[R_NEXT]], [[B]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ugt i64 %start, 2
  br i1 %pre, label %loop, label %exit

loop:
  %r = phi i64 [ %start, %entry ], [ %r.next, %loop ]
  %b = load i64, ptr %p
  %c = icmp ugt i64 %r, 2
  call void @use(i1 %c)
  %r.next = lshr i64 %r, 1
  %ec = icmp ugt i64 %r.next, %b
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}
