; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)
declare i1 @cond(i64)

; Binary search: hi steps to mid = lo + ((hi - lo) >> 1) or stays, so it never
; exceeds its start n, and mid < n < size.
define void @binary_search_midpoint(i64 %n, i64 %size) {
; CHECK-LABEL: define void @binary_search_midpoint(
; CHECK-SAME: i64 [[N:%.*]], i64 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[N_LT_SIZE:%.*]] = icmp ult i64 [[N]], [[SIZE]]
; CHECK-NEXT:    br i1 [[N_LT_SIZE]], label %[[LOOP:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LO:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[LO_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[LO_LT_HI:%.*]] = icmp ult i64 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[LO_LT_HI]], label %[[BODY:.*]], label %[[EXIT]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[MID:%.*]] = add nuw i64 [[H]], [[LO]]
; CHECK-NEXT:    br i1 true, label %[[LATCH]], label %[[TRAP:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[MID]])
; CHECK-NEXT:    [[MID_1:%.*]] = add nuw i64 [[MID]], 1
; CHECK-NEXT:    [[LO_NEXT]] = select i1 [[C]], i64 [[LO]], i64 [[MID_1]]
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[MID]], i64 [[HI]]
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %n.lt.size = icmp ult i64 %n, %size
  br i1 %n.lt.size, label %loop, label %exit

loop:
  %lo = phi i64 [ 0, %entry ], [ %lo.next, %latch ]
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %latch ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %lo.lt.hi = icmp ult i64 %lo, %hi
  br i1 %lo.lt.hi, label %body, label %exit

body:
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, 1
  %mid = add nuw i64 %h, %lo
  %in.bounds = icmp ult i64 %mid, %size
  br i1 %in.bounds, label %latch, label %trap

latch:
  %c = call i1 @cond(i64 %mid)
  %mid.1 = add nuw i64 %mid, 1
  %lo.next = select i1 %c, i64 %lo, i64 %mid.1
  %hi.next = select i1 %c, i64 %mid, i64 %hi
  br label %loop

trap:
  call void @llvm.trap()
  unreachable

exit:
  ret void
}

; hi steps to hi -nuw k or stays.
define void @select_sub_nuw_step(i64 %n, i64 %k) {
; CHECK-LABEL: define void @select_sub_nuw_step(
; CHECK-SAME: i64 [[N:%.*]], i64 [[K:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[HI]])
; CHECK-NEXT:    [[DEC:%.*]] = sub nuw i64 [[HI]], [[K]]
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[DEC]], i64 [[HI]]
; CHECK-NEXT:    [[DONE:%.*]] = call i1 @cond(i64 [[HI_NEXT]])
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %c = call i1 @cond(i64 %hi)
  %dec = sub nuw i64 %hi, %k
  %hi.next = select i1 %c, i64 %dec, i64 %hi
  %done = call i1 @cond(i64 %hi.next)
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; hi steps to hi >>u 1 or stays (select operands swapped).
define void @select_lshr_step(i64 %n) {
; CHECK-LABEL: define void @select_lshr_step(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[HI]])
; CHECK-NEXT:    [[HALF:%.*]] = lshr i64 [[HI]], 1
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[HI]], i64 [[HALF]]
; CHECK-NEXT:    [[DONE:%.*]] = call i1 @cond(i64 [[HI_NEXT]])
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %c = call i1 @cond(i64 %hi)
  %half = lshr i64 %hi, 1
  %hi.next = select i1 %c, i64 %hi, i64 %half
  %done = call i1 @cond(i64 %hi.next)
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: hi + 1 can exceed hi.
define void @select_add_step(i64 %n) {
; CHECK-LABEL: define void @select_add_step(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[HI]])
; CHECK-NEXT:    [[INC:%.*]] = add nuw i64 [[HI]], 1
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[INC]], i64 [[HI]]
; CHECK-NEXT:    [[DONE:%.*]] = call i1 @cond(i64 [[HI_NEXT]])
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %c = call i1 @cond(i64 %hi)
  %inc = add nuw i64 %hi, 1
  %hi.next = select i1 %c, i64 %inc, i64 %hi
  %done = call i1 @cond(i64 %hi.next)
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: hi - k without nuw can wrap above hi.
define void @select_sub_no_nuw_step(i64 %n, i64 %k) {
; CHECK-LABEL: define void @select_sub_no_nuw_step(
; CHECK-SAME: i64 [[N:%.*]], i64 [[K:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[HI]])
; CHECK-NEXT:    [[DEC:%.*]] = sub i64 [[HI]], [[K]]
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[DEC]], i64 [[HI]]
; CHECK-NEXT:    [[DONE:%.*]] = call i1 @cond(i64 [[HI_NEXT]])
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %c = call i1 @cond(i64 %hi)
  %dec = sub i64 %hi, %k
  %hi.next = select i1 %c, i64 %dec, i64 %hi
  %done = call i1 @cond(i64 %hi.next)
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: the midpoint is only recognized with nuw on the add.
define void @select_midpoint_add_no_nuw(i64 %lo, i64 %n) {
; CHECK-LABEL: define void @select_midpoint_add_no_nuw(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[HI]])
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[MID:%.*]] = add i64 [[H]], [[LO]]
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[MID]], i64 [[HI]]
; CHECK-NEXT:    [[DONE:%.*]] = call i1 @cond(i64 [[HI_NEXT]])
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %c = call i1 @cond(i64 %hi)
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, 1
  %mid = add i64 %h, %lo
  %hi.next = select i1 %c, i64 %mid, i64 %hi
  %done = call i1 @cond(i64 %hi.next)
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: the midpoint's subtrahend is not the value added back.
define void @select_midpoint_mismatch(i64 %lo, i64 %x, i64 %n) {
; CHECK-LABEL: define void @select_midpoint_mismatch(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[X:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[HI:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[HI_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[HI_LE_N:%.*]] = icmp ule i64 [[HI]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[HI_LE_N]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond(i64 [[HI]])
; CHECK-NEXT:    [[D:%.*]] = sub nuw i64 [[HI]], [[LO]]
; CHECK-NEXT:    [[H:%.*]] = lshr i64 [[D]], 1
; CHECK-NEXT:    [[MID:%.*]] = add nuw i64 [[H]], [[X]]
; CHECK-NEXT:    [[HI_NEXT]] = select i1 [[C]], i64 [[MID]], i64 [[HI]]
; CHECK-NEXT:    [[DONE:%.*]] = call i1 @cond(i64 [[HI_NEXT]])
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %hi = phi i64 [ %n, %entry ], [ %hi.next, %loop ]
  %hi.le.n = icmp ule i64 %hi, %n
  call void @use(i1 %hi.le.n)
  %c = call i1 @cond(i64 %hi)
  %d = sub nuw i64 %hi, %lo
  %h = lshr i64 %d, 1
  %mid = add nuw i64 %h, %x
  %hi.next = select i1 %c, i64 %mid, i64 %hi
  %done = call i1 @cond(i64 %hi.next)
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

declare void @llvm.trap()
