; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)
declare void @use.agg({ i8, i1 })

; A is in [0, 100), so A + 1 does not signed-overflow (A s<= SMAX - 1).
define i8 @sadd_no_overflow_pos_const(i8 %a) {
; CHECK-LABEL: define i8 @sadd_no_overflow_pos_const(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i8 [[A]], 100
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[OK]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], 1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sge i8 %a, 0
  %hi = icmp slt i8 %a, 100
  %ok = and i1 %lo, %hi
  br i1 %ok, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; A is in (-100, 0], so A + (-1) does not signed-overflow (A s>= SMIN + 1).
define i8 @sadd_no_overflow_neg_const(i8 %a) {
; CHECK-LABEL: define i8 @sadd_no_overflow_neg_const(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sgt i8 [[A]], -100
; CHECK-NEXT:    [[HI:%.*]] = icmp sle i8 [[A]], 0
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[OK]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], -1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sgt i8 %a, -100
  %hi = icmp sle i8 %a, 0
  %ok = and i1 %lo, %hi
  br i1 %ok, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 -1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; A only known non-negative, no upper bound, so A + 1 may overflow.
define i8 @sadd_may_overflow(i8 %a) {
; CHECK-LABEL: define i8 @sadd_may_overflow(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    br i1 [[LO]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 1)
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i8, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i8, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sge i8 %a, 0
  br i1 %lo, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}


define void @sadd_result_guarded_nonneg_ops(i8 %a, i8 %b) {
;
; CHECK-LABEL: define void @sadd_result_guarded_nonneg_ops(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT:.*]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %exit, label %no.ov

no.ov:
  %s = extractvalue { i8, i1 } %wo, 0
  %t.1 = icmp sge i8 %s, 0
  call void @use(i1 %t.1)
  %t.2 = icmp sge i8 %s, %a
  call void @use(i1 %t.2)
  %t.3 = icmp uge i8 %s, %b
  call void @use(i1 %t.3)
  ret void

exit:
  ret void
}

define i1 @sadd_result_guarded_srem_index(i8 %i, i8 %off, i8 %n, i8 %d) {
;
; CHECK-LABEL: define i1 @sadd_result_guarded_srem_index(
; CHECK-SAME: i8 [[I:%.*]], i8 [[OFF:%.*]], i8 [[N:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[I_NONNEG:%.*]] = icmp sge i8 [[I]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[I_NONNEG]])
; CHECK-NEXT:    [[OFF_NONNEG:%.*]] = icmp sge i8 [[OFF]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[OFF_NONNEG]])
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sgt i8 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[N_POS]])
; CHECK-NEXT:    [[N_ULE_D:%.*]] = icmp ule i8 [[N]], [[D]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[N_ULE_D]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[I]], i8 [[OFF]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT:.*]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    [[IDX:%.*]] = srem i8 [[S]], [[N]]
; CHECK-NEXT:    ret i1 true
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %i.nonneg = icmp sge i8 %i, 0
  call void @llvm.assume(i1 %i.nonneg)
  %off.nonneg = icmp sge i8 %off, 0
  call void @llvm.assume(i1 %off.nonneg)
  %n.pos = icmp sgt i8 %n, 0
  call void @llvm.assume(i1 %n.pos)
  %n.ule.d = icmp ule i8 %n, %d
  call void @llvm.assume(i1 %n.ule.d)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %i, i8 %off)
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %exit, label %no.ov

no.ov:
  %s = extractvalue { i8, i1 } %wo, 0
  %idx = srem i8 %s, %n
  %t = icmp ult i8 %idx, %d
  ret i1 %t

exit:
  ret i1 false
}

define void @sadd_result_used_on_overflow(i8 %a, i8 %b) {
;
; CHECK-LABEL: define void @sadd_result_used_on_overflow(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[OVF:.*]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
; CHECK:       [[OVF]]:
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[S]], 0
; CHECK-NEXT:    call void @use(i1 [[C_2]])
; CHECK-NEXT:    ret void
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %s = extractvalue { i8, i1 } %wo, 0
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %ovf, label %no.ov

no.ov:
  %c.1 = icmp sge i8 %s, 0
  call void @use(i1 %c.1)
  ret void

ovf:
  %c.2 = icmp sge i8 %s, 0
  call void @use(i1 %c.2)
  ret void
}

define void @sadd_result_guarded_unsigned_neg_op(i8 %a, i8 %b) {
;
; CHECK-LABEL: define void @sadd_result_guarded_unsigned_neg_op(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT:.*]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    [[C:%.*]] = icmp uge i8 [[S]], [[A]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    ret void
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %exit, label %no.ov

no.ov:
  %s = extractvalue { i8, i1 } %wo, 0
  %c = icmp uge i8 %s, %a
  call void @use(i1 %c)
  ret void

exit:
  ret void
}

define void @sadd_result_in_fact_before_guard(i8 %a, i8 %b, i8 %n) {
;
; CHECK-LABEL: define void @sadd_result_in_fact_before_guard(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]], i8 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    [[C_0:%.*]] = icmp sle i8 [[S]], [[N]]
; CHECK-NEXT:    br i1 [[C_0]], label %[[GUARD:.*]], label %[[EXIT:.*]]
; CHECK:       [[GUARD]]:
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %s = extractvalue { i8, i1 } %wo, 0
  %c.0 = icmp sle i8 %s, %n
  br i1 %c.0, label %guard, label %exit

guard:
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %exit, label %no.ov

no.ov:
  %c.1 = icmp sle i8 %a, %n
  call void @use(i1 %c.1)
  ret void

exit:
  ret void
}

define void @sadd_no_ov_succ_has_other_pred(i8 %a, i8 %b) {
;
; CHECK-LABEL: define void @sadd_no_ov_succ_has_other_pred(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[OVF:.*]], label %[[JOIN:.*]]
; CHECK:       [[OVF]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp sge i8 [[S]], 0
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %s = extractvalue { i8, i1 } %wo, 0
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %ovf, label %join

ovf:
  br label %join

join:
  %c = icmp sge i8 %s, 0
  call void @use(i1 %c)
  ret void
}

define void @sadd_result_used_after_merge(i8 %a, i8 %b) {
;
; CHECK-LABEL: define void @sadd_result_used_after_merge(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[OVF:.*]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[OVF]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[S]], 0
; CHECK-NEXT:    call void @use(i1 [[C_2]])
; CHECK-NEXT:    ret void
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %wo = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %s = extractvalue { i8, i1 } %wo, 0
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %ovf, label %no.ov

no.ov:
  %c.1 = icmp sge i8 %s, 0
  call void @use(i1 %c.1)
  br label %join

ovf:
  br label %join

join:
  %c.2 = icmp sge i8 %s, 0
  call void @use(i1 %c.2)
  ret void
}

; C == SMIN, so A + C does not signed-overflow iff A s>= 0.
define i8 @sadd_c_smin(i8 %a) {
; CHECK-LABEL: define i8 @sadd_c_smin(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    br i1 [[LO]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], -128
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sge i8 %a, 0
  br i1 %lo, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 -128)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; C == SMAX, so A + C does not signed-overflow iff A s<= 0.
define i8 @sadd_c_smax(i8 %a) {
; CHECK-LABEL: define i8 @sadd_c_smax(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[HI:%.*]] = icmp sle i8 [[A]], 0
; CHECK-NEXT:    br i1 [[HI]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], 127
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %hi = icmp sle i8 %a, 0
  br i1 %hi, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 127)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; The upper bound is one too large.
define i8 @sadd_pos_const_bound_too_large(i8 %a) {
; CHECK-LABEL: define i8 @sadd_pos_const_bound_too_large(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[HI:%.*]] = icmp sle i8 [[A]], 127
; CHECK-NEXT:    br i1 [[HI]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 1)
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i8, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i8, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %hi = icmp sle i8 %a, 127
  br i1 %hi, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; The lower bound is one too small.
define i8 @sadd_neg_const_bound_too_small(i8 %a) {
; CHECK-LABEL: define i8 @sadd_neg_const_bound_too_small(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], -128
; CHECK-NEXT:    br i1 [[LO]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 -1)
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i8, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i8, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sge i8 %a, -128
  br i1 %lo, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 -1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

define i8 @sadd_unsigned_bound(i8 %a) {
; CHECK-LABEL: define i8 @sadd_unsigned_bound(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[HI:%.*]] = icmp ult i8 [[A]], 100
; CHECK-NEXT:    br i1 [[HI]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], 1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %hi = icmp ult i8 %a, 100
  br i1 %hi, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; The second operand is not a constant.
define i8 @sadd_variable_ops(i8 %a, i8 %b) {
; CHECK-LABEL: define i8 @sadd_variable_ops(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i8 [[A]], 100
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[OK]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i8, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i8, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sge i8 %a, 0
  %hi = icmp slt i8 %a, 100
  %ok = and i1 %lo, %hi
  br i1 %ok, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

define i8 @sadd_aggregate_escapes(i8 %a) {
; CHECK-LABEL: define i8 @sadd_aggregate_escapes(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i8 [[A]], 100
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[OK]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], 1
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 1)
; CHECK-NEXT:    call void @use.agg({ i8, i1 } [[S]])
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %lo = icmp sge i8 %a, 0
  %hi = icmp slt i8 %a, 100
  %ok = and i1 %lo, %hi
  br i1 %ok, label %then, label %else

then:
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use.agg({ i8, i1 } %s)
  call void @use(i1 %o)
  ret i8 %v

else:
  ret i8 0
}

; Operands of different signs do not overflow.
define i8 @sadd_nonneg_nonpos_ops(i8 %a, i8 %b) {
; CHECK-LABEL: define i8 @sadd_nonneg_nonpos_ops(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONPOS:%.*]] = icmp sle i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONPOS]])
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[TMP0]]
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonpos = icmp sle i8 %b, 0
  call void @llvm.assume(i1 %b.nonpos)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

define i8 @sadd_nonpos_nonneg_ops(i8 %a, i8 %b) {
; CHECK-LABEL: define i8 @sadd_nonpos_nonneg_ops(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONPOS:%.*]] = icmp sle i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONPOS]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[TMP0]]
;
entry:
  %a.nonpos = icmp sle i8 %a, 0
  call void @llvm.assume(i1 %a.nonpos)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

define i8 @sadd_nonneg_ops(i8 %a, i8 %b) {
; CHECK-LABEL: define i8 @sadd_nonneg_ops(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_NONNEG:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[A_NONNEG]])
; CHECK-NEXT:    [[B_NONNEG:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[B_NONNEG]])
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i8, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i8, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i8 [[V]]
;
entry:
  %a.nonneg = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %a.nonneg)
  %b.nonneg = icmp sge i8 %b, 0
  call void @llvm.assume(i1 %b.nonneg)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 %b)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; A s< N - 1 with N s<= SMAX, so A + 1 does not signed-overflow. SMAX does not
; fit a constraint row, so this uses the type bound of N.
define i64 @sadd_type_bound_upper(i64 %a, i64 %n) {
; CHECK-LABEL: define i64 @sadd_type_bound_upper(
; CHECK-SAME: i64 [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_MINUS_1:%.*]] = add nsw i64 [[N]], -1
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[A]], [[N_MINUS_1]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i64 [[A]], 1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i64 [[TMP0]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %n.minus.1 = add nsw i64 %n, -1
  %c = icmp slt i64 %a, %n.minus.1
  br i1 %c, label %then, label %else

then:
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 1)
  %v = extractvalue { i64, i1 } %s, 0
  %o = extractvalue { i64, i1 } %s, 1
  call void @use(i1 %o)
  ret i64 %v

else:
  ret i64 0
}

; A s> N with N s>= SMIN, so A + (-1) does not signed-overflow.
define i64 @sadd_type_bound_lower(i64 %a, i64 %n) {
; CHECK-LABEL: define i64 @sadd_type_bound_lower(
; CHECK-SAME: i64 [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i64 [[A]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i64 [[A]], -1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i64 [[TMP0]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %c = icmp sgt i64 %a, %n
  br i1 %c, label %then, label %else

then:
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 -1)
  %v = extractvalue { i64, i1 } %s, 0
  %o = extractvalue { i64, i1 } %s, 1
  call void @use(i1 %o)
  ret i64 %v

else:
  ret i64 0
}

; A s<= N allows A == N == SMAX.
define i64 @sadd_type_bound_upper_le(i64 %a, i64 %n) {
; CHECK-LABEL: define i64 @sadd_type_bound_upper_le(
; CHECK-SAME: i64 [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp sle i64 [[A]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[S:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 1)
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i64, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i64, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i64 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %c = icmp sle i64 %a, %n
  br i1 %c, label %then, label %else

then:
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 1)
  %v = extractvalue { i64, i1 } %s, 0
  %o = extractvalue { i64, i1 } %s, 1
  call void @use(i1 %o)
  ret i64 %v

else:
  ret i64 0
}

; A s< N - 1 with N an i8, so A + 2 s<= 127.
define i64 @sadd_type_bound_narrow_var(i64 %a, i8 %n) {
; CHECK-LABEL: define i64 @sadd_type_bound_narrow_var(
; CHECK-SAME: i64 [[A:%.*]], i8 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_EXT:%.*]] = sext i8 [[N]] to i64
; CHECK-NEXT:    [[N_MINUS_1:%.*]] = add nsw i64 [[N_EXT]], -1
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[A]], [[N_MINUS_1]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i64 [[A]], 2
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i64 [[TMP0]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %n.ext = sext i8 %n to i64
  %n.minus.1 = add nsw i64 %n.ext, -1
  %c = icmp slt i64 %a, %n.minus.1
  br i1 %c, label %then, label %else

then:
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 2)
  %v = extractvalue { i64, i1 } %s, 0
  %o = extractvalue { i64, i1 } %s, 1
  call void @use(i1 %o)
  ret i64 %v

else:
  ret i64 0
}

; N is wider than A, so its type bound does not bound A + 1.
define i32 @sadd_type_bound_wide_var(i32 %a, i64 %n) {
; CHECK-LABEL: define i32 @sadd_type_bound_wide_var(
; CHECK-SAME: i32 [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_EXT:%.*]] = sext i32 [[A]] to i64
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[A_EXT]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[S:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A]], i32 1)
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i32, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i32, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i32 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %a.ext = sext i32 %a to i64
  %c = icmp slt i64 %a.ext, %n
  br i1 %c, label %then, label %else

then:
  %s = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 %a, i32 1)
  %v = extractvalue { i32, i1 } %s, 0
  %o = extractvalue { i32, i1 } %s, 1
  call void @use(i1 %o)
  ret i32 %v

else:
  ret i32 0
}
