; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)

define void @uadd_result_guarded(i8 %a, i8 %b) {
;
; CHECK-LABEL: define void @uadd_result_guarded(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WO:%.*]] = call { i8, i1 } @llvm.uadd.with.overflow.i8(i8 [[A]], i8 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i8, i1 } [[WO]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT:.*]], label %[[NO_OV:.*]]
; CHECK:       [[NO_OV]]:
; CHECK-NEXT:    [[S:%.*]] = extractvalue { i8, i1 } [[WO]], 0
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %wo = call { i8, i1 } @llvm.uadd.with.overflow.i8(i8 %a, i8 %b)
  %ov = extractvalue { i8, i1 } %wo, 1
  br i1 %ov, label %exit, label %no.ov

no.ov:
  %s = extractvalue { i8, i1 } %wo, 0
  %t = icmp uge i8 %s, %a
  call void @use(i1 %t)
  ret void

exit:
  ret void
}
