; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='default<O3>' -S %s | FileCheck %s

; libc++ std::midpoint for unsigned values computes lo + ((hi - lo) >> 1).
; With nuw on the add, ConstraintElimination proves mid <= hi < size, so
; the bounds check folds.
define i1 @midpoint_bounds_check(i64 %lo, i64 %hi, i64 %size) {
; CHECK-LABEL: define i1 @midpoint_bounds_check(
; CHECK-SAME: i64 [[LO:%.*]], i64 [[HI:%.*]], i64 [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LO_LE_HI:%.*]] = icmp ule i64 [[LO]], [[HI]]
; CHECK-NEXT:    [[HI_LT_SIZE:%.*]] = icmp ult i64 [[HI]], [[SIZE]]
; CHECK-NEXT:    [[PRE:%.*]] = and i1 [[LO_LE_HI]], [[HI_LT_SIZE]]
; CHECK-NEXT:    ret i1 [[PRE]]
;
entry:
  %lo.le.hi = icmp ule i64 %lo, %hi
  %hi.lt.size = icmp ult i64 %hi, %size
  %pre = and i1 %lo.le.hi, %hi.lt.size
  br i1 %pre, label %body, label %exit

body:
  %d = sub i64 %hi, %lo
  %h = lshr i64 %d, 1
  %mid = add i64 %h, %lo
  %in.bounds = icmp ult i64 %mid, %size
  br i1 %in.bounds, label %ok, label %trap

ok:
  ret i1 true

trap:
  call void @llvm.trap()
  unreachable

exit:
  ret i1 false
}

declare void @llvm.trap()
