// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// REQUIRES: system-darwin

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -Wno-error=incompatible-pointer-types -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -Wno-error=incompatible-pointer-types -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -Wno-error=incompatible-pointer-types -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -Wno-error=incompatible-pointer-types -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s

struct S {
    int *p;
    long i;
};

void foo(int * a, long i) {
    struct S s = {a, i};
    struct S *sp = &s.i; // bad cast but we don't check
bingo:;
    sp->i = 3; // run-time trap : oob
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// O0: {{.*}}
// O2: {{.*}}
