; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=indvars -S < %s | FileCheck %s

; The exit `iv u< len` with iv = {0,+,stride} is checked against the guard
; `(n - 1) * stride u< len`. n and stride are below 2^32, so the IV does not
; wrap in the first n iterations.

declare void @use(i64)

define void @stride_check_guarded_last_iter(i64 %n, i64 %stride, i64 %len) {
; CHECK-LABEL: define void @stride_check_guarded_last_iter(
; CHECK-SAME: i64 [[N:%.*]], i64 [[STRIDE:%.*]], i64 [[LEN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_SMALL:%.*]] = icmp ult i64 [[N]], 4294967296
; CHECK-NEXT:    [[STRIDE_SMALL:%.*]] = icmp ult i64 [[STRIDE]], 4294967296
; CHECK-NEXT:    [[SMALL:%.*]] = and i1 [[N_SMALL]], [[STRIDE_SMALL]]
; CHECK-NEXT:    br i1 [[SMALL]], label %[[GUARD:.*]], label %[[EXIT:.*]]
; CHECK:       [[GUARD]]:
; CHECK-NEXT:    [[N_MINUS_1:%.*]] = add i64 [[N]], -1
; CHECK-NEXT:    [[LAST:%.*]] = mul i64 [[N_MINUS_1]], [[STRIDE]]
; CHECK-NEXT:    [[LAST_IN_BOUNDS:%.*]] = icmp ult i64 [[LAST]], [[LEN]]
; CHECK-NEXT:    [[N_NONZERO:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    [[ENTER:%.*]] = and i1 [[LAST_IN_BOUNDS]], [[N_NONZERO]]
; CHECK-NEXT:    br i1 [[ENTER]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IDX:%.*]] = mul i64 [[I]], [[STRIDE]]
; CHECK-NEXT:    br i1 true, label %[[LATCH]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    call void @use(i64 [[IDX]])
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %n.small = icmp ult i64 %n, 4294967296
  %stride.small = icmp ult i64 %stride, 4294967296
  %small = and i1 %n.small, %stride.small
  br i1 %small, label %guard, label %exit

guard:
  %n.minus.1 = add i64 %n, -1
  %last = mul i64 %n.minus.1, %stride
  %last.in.bounds = icmp ult i64 %last, %len
  %n.nonzero = icmp ne i64 %n, 0
  %enter = and i1 %last.in.bounds, %n.nonzero
  br i1 %enter, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %guard ], [ %i.next, %latch ]
  %idx = mul i64 %i, %stride
  %in.bounds = icmp ult i64 %idx, %len
  br i1 %in.bounds, label %latch, label %exit

latch:
  call void @use(i64 %idx)
  %i.next = add nuw i64 %i, 1
  %cont = icmp ult i64 %i.next, %n
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; No bound on stride: (n - 1) * stride may overflow.
define void @stride_unbounded(i64 %n, i64 %stride, i64 %len) {
; CHECK-LABEL: define void @stride_unbounded(
; CHECK-SAME: i64 [[N:%.*]], i64 [[STRIDE:%.*]], i64 [[LEN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_SMALL:%.*]] = icmp ult i64 [[N]], 4294967296
; CHECK-NEXT:    br i1 [[N_SMALL]], label %[[GUARD:.*]], label %[[EXIT:.*]]
; CHECK:       [[GUARD]]:
; CHECK-NEXT:    [[N_MINUS_1:%.*]] = add i64 [[N]], -1
; CHECK-NEXT:    [[LAST:%.*]] = mul i64 [[N_MINUS_1]], [[STRIDE]]
; CHECK-NEXT:    [[LAST_IN_BOUNDS:%.*]] = icmp ult i64 [[LAST]], [[LEN]]
; CHECK-NEXT:    [[N_NONZERO:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    [[ENTER:%.*]] = and i1 [[LAST_IN_BOUNDS]], [[N_NONZERO]]
; CHECK-NEXT:    br i1 [[ENTER]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IDX:%.*]] = mul i64 [[I]], [[STRIDE]]
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[IDX]], [[LEN]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label %[[LATCH]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    call void @use(i64 [[IDX]])
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %n.small = icmp ult i64 %n, 4294967296
  br i1 %n.small, label %guard, label %exit

guard:
  %n.minus.1 = add i64 %n, -1
  %last = mul i64 %n.minus.1, %stride
  %last.in.bounds = icmp ult i64 %last, %len
  %n.nonzero = icmp ne i64 %n, 0
  %enter = and i1 %last.in.bounds, %n.nonzero
  br i1 %enter, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %guard ], [ %i.next, %latch ]
  %idx = mul i64 %i, %stride
  %in.bounds = icmp ult i64 %idx, %len
  br i1 %in.bounds, label %latch, label %exit

latch:
  call void @use(i64 %idx)
  %i.next = add nuw i64 %i, 1
  %cont = icmp ult i64 %i.next, %n
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; The guard `(n - 1) * stride u<= len` allows idx == len.
define void @stride_guard_ule(i64 %n, i64 %stride, i64 %len) {
; CHECK-LABEL: define void @stride_guard_ule(
; CHECK-SAME: i64 [[N:%.*]], i64 [[STRIDE:%.*]], i64 [[LEN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_SMALL:%.*]] = icmp ult i64 [[N]], 4294967296
; CHECK-NEXT:    [[STRIDE_SMALL:%.*]] = icmp ult i64 [[STRIDE]], 4294967296
; CHECK-NEXT:    [[SMALL:%.*]] = and i1 [[N_SMALL]], [[STRIDE_SMALL]]
; CHECK-NEXT:    br i1 [[SMALL]], label %[[GUARD:.*]], label %[[EXIT:.*]]
; CHECK:       [[GUARD]]:
; CHECK-NEXT:    [[N_MINUS_1:%.*]] = add i64 [[N]], -1
; CHECK-NEXT:    [[LAST:%.*]] = mul i64 [[N_MINUS_1]], [[STRIDE]]
; CHECK-NEXT:    [[LAST_IN_BOUNDS:%.*]] = icmp ule i64 [[LAST]], [[LEN]]
; CHECK-NEXT:    [[N_NONZERO:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    [[ENTER:%.*]] = and i1 [[LAST_IN_BOUNDS]], [[N_NONZERO]]
; CHECK-NEXT:    br i1 [[ENTER]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IDX:%.*]] = mul i64 [[I]], [[STRIDE]]
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[IDX]], [[LEN]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label %[[LATCH]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    call void @use(i64 [[IDX]])
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %n.small = icmp ult i64 %n, 4294967296
  %stride.small = icmp ult i64 %stride, 4294967296
  %small = and i1 %n.small, %stride.small
  br i1 %small, label %guard, label %exit

guard:
  %n.minus.1 = add i64 %n, -1
  %last = mul i64 %n.minus.1, %stride
  %last.in.bounds = icmp ule i64 %last, %len
  %n.nonzero = icmp ne i64 %n, 0
  %enter = and i1 %last.in.bounds, %n.nonzero
  br i1 %enter, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %guard ], [ %i.next, %latch ]
  %idx = mul i64 %i, %stride
  %in.bounds = icmp ult i64 %idx, %len
  br i1 %in.bounds, label %latch, label %exit

latch:
  call void @use(i64 %idx)
  %i.next = add nuw i64 %i, 1
  %cont = icmp ult i64 %i.next, %n
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}
