; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=indvars -S < %s | FileCheck %s

; The header exit (i == n) dominates the overflow exit and its exit count
; n is u<= the overflow exit count INT_MAX, so the overflow exit is never taken.
define i64 @dominating_exit_count_ule(i64 %n) {
; CHECK-LABEL: define i64 @dominating_exit_count_ule(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[N_NONNEG:%.*]] = icmp sge i64 [[N]], 0
; CHECK-NEXT:    br i1 [[N_NONNEG]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[CHECK:.*]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    [[ADD:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[IV]], i64 1)
; CHECK-NEXT:    br i1 false, label %[[TRAP:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = extractvalue { i64, i1 } [[ADD]], 0
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[IV_LCSSA:%.*]] = phi i64 [ [[N]], %[[LOOP]] ], [ [[IV]], %[[LATCH]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ -1, %[[ENTRY]] ], [ [[IV_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i64 [[R]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %n.nonneg = icmp sge i64 %n, 0
  br i1 %n.nonneg, label %loop, label %exit

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %done = icmp eq i64 %iv, %n
  br i1 %done, label %exit, label %check

check:
  %add = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 1)
  %ov = extractvalue { i64, i1 } %add, 1
  br i1 %ov, label %trap, label %latch

latch:
  %iv.next = extractvalue { i64, i1 } %add, 0
  %c = call i1 @cond()
  br i1 %c, label %loop, label %exit

exit:
  %r = phi i64 [ -1, %entry ], [ %iv, %loop ], [ %iv, %latch ]
  ret i64 %r

trap:
  call void @llvm.trap()
  unreachable
}

; Negative test: without n >= 0, n may exceed INT_MAX as an unsigned count.
define i64 @dominating_exit_count_not_ule(i64 %n) {
; CHECK-LABEL: define i64 @dominating_exit_count_not_ule(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[CHECK:.*]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    [[ADD:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[IV]], i64 1)
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[ADD]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = extractvalue { i64, i1 } [[ADD]], 0
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[N]], %[[LOOP]] ], [ [[IV]], %[[LATCH]] ]
; CHECK-NEXT:    ret i64 [[R]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %done = icmp eq i64 %iv, %n
  br i1 %done, label %exit, label %check

check:
  %add = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 1)
  %ov = extractvalue { i64, i1 } %add, 1
  br i1 %ov, label %trap, label %latch

latch:
  %iv.next = extractvalue { i64, i1 } %add, 0
  %c = call i1 @cond()
  br i1 %c, label %loop, label %exit

exit:
  %r = phi i64 [ %iv, %loop ], [ %iv, %latch ]
  ret i64 %r

trap:
  call void @llvm.trap()
  unreachable
}

declare i1 @cond()
