; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=indvars -S < %s | FileCheck %s

; The exit `idx u< len` with idx = {0,+,2} is checked against loop guards on
; n. The value on the last iteration is 2 * n - 2.

declare void @use(i64)

; Guard 2 * n u<= len with n u< 2^32: Last + 2 = 2 * n does not wrap.
define void @step2_guard_mul(i64 %n, i64 %len) {
; CHECK-LABEL: define void @step2_guard_mul(
; CHECK-SAME: i64 [[N:%.*]], i64 [[LEN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_SMALL:%.*]] = icmp ult i64 [[N]], 4294967296
; CHECK-NEXT:    br i1 [[N_SMALL]], label %[[GUARD:.*]], label %[[EXIT:.*]]
; CHECK:       [[GUARD]]:
; CHECK-NEXT:    [[TWICE_N:%.*]] = shl i64 [[N]], 1
; CHECK-NEXT:    [[FITS:%.*]] = icmp ule i64 [[TWICE_N]], [[LEN]]
; CHECK-NEXT:    [[N_NONZERO:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    [[ENTER:%.*]] = and i1 [[FITS]], [[N_NONZERO]]
; CHECK-NEXT:    br i1 [[ENTER]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    [[IN_BOUNDS_FIRST_ITER:%.*]] = icmp ult i64 0, [[LEN]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IDX:%.*]] = shl nuw nsw i64 [[I]], 1
; CHECK-NEXT:    br i1 [[IN_BOUNDS_FIRST_ITER]], label %[[LATCH]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    call void @use(i64 [[IDX]])
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %n.small = icmp ult i64 %n, 4294967296
  br i1 %n.small, label %guard, label %exit

guard:
  %twice.n = shl i64 %n, 1
  %fits = icmp ule i64 %twice.n, %len
  %n.nonzero = icmp ne i64 %n, 0
  %enter = and i1 %fits, %n.nonzero
  br i1 %enter, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %guard ], [ %i.next, %latch ]
  %idx = shl nuw nsw i64 %i, 1
  %in.bounds = icmp ult i64 %idx, %len
  br i1 %in.bounds, label %latch, label %exit

latch:
  call void @use(i64 %idx)
  %i.next = add nuw i64 %i, 1
  %cont = icmp ult i64 %i.next, %n
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}

; No bound on n: 2 * n may wrap, so 2 * n u<= len does not bound idx.
define void @step2_guard_mul_unbounded(i64 %n, i64 %len) {
; CHECK-LABEL: define void @step2_guard_mul_unbounded(
; CHECK-SAME: i64 [[N:%.*]], i64 [[LEN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TWICE_N:%.*]] = shl i64 [[N]], 1
; CHECK-NEXT:    [[FITS:%.*]] = icmp ule i64 [[TWICE_N]], [[LEN]]
; CHECK-NEXT:    [[N_NONZERO:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    [[ENTER:%.*]] = and i1 [[FITS]], [[N_NONZERO]]
; CHECK-NEXT:    br i1 [[ENTER]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IDX:%.*]] = shl i64 [[I]], 1
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp ult i64 [[IDX]], [[LEN]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label %[[LATCH]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    call void @use(i64 [[IDX]])
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %twice.n = shl i64 %n, 1
  %fits = icmp ule i64 %twice.n, %len
  %n.nonzero = icmp ne i64 %n, 0
  %enter = and i1 %fits, %n.nonzero
  br i1 %enter, label %loop, label %exit

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %latch ]
  %idx = shl i64 %i, 1
  %in.bounds = icmp ult i64 %idx, %len
  br i1 %in.bounds, label %latch, label %exit

latch:
  call void @use(i64 %idx)
  %i.next = add nuw i64 %i, 1
  %cont = icmp ult i64 %i.next, %n
  br i1 %cont, label %loop, label %exit

exit:
  ret void
}
