; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=indvars -S < %s | FileCheck %s

; %n != SMAX on the switch default edge bounds iv + 2 below SMAX, so
; iv s< 0 is false.
define i1 @iv_stride2_nonneg_switch_ne_smax(ptr %p, i64 %n) {
; CHECK-LABEL: @iv_stride2_nonneg_switch_ne_smax(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[N_NONNEG:%.*]] = icmp sgt i64 [[N:%.*]], -1
; CHECK-NEXT:    call void @llvm.assume(i1 [[N_NONNEG]])
; CHECK-NEXT:    switch i64 [[N]], label [[LOOP_PREHEADER:%.*]] [
; CHECK-NEXT:      i64 9223372036854775807, label [[EXIT:%.*]]
; CHECK-NEXT:      i64 0, label [[EXIT]]
; CHECK-NEXT:    ]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IV_OR_1:%.*]] = or disjoint i64 [[IV]], 1
; CHECK-NEXT:    [[IN_BOUNDS:%.*]] = icmp slt i64 [[IV_OR_1]], [[N]]
; CHECK-NEXT:    br i1 [[IN_BOUNDS]], label [[CHECK:%.*]], label [[LATCH]]
; CHECK:       check:
; CHECK-NEXT:    br i1 false, label [[TRAP:%.*]], label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr [[P:%.*]], i64 [[IV_OR_1]]
; CHECK-NEXT:    [[V:%.*]] = load i8, ptr [[GEP]], align 1
; CHECK-NEXT:    [[FOUND:%.*]] = icmp eq i8 [[V]], 0
; CHECK-NEXT:    br i1 [[FOUND]], label [[EXIT_LOOPEXIT:%.*]], label [[LATCH]]
; CHECK:       latch:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 2
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    [[R_PH:%.*]] = phi i1 [ true, [[BODY]] ], [ false, [[LATCH]] ]
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ false, [[ENTRY:%.*]] ], [ false, [[ENTRY]] ], [ [[R_PH]], [[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i1 [[R]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
;
entry:
  %n.nonneg = icmp sgt i64 %n, -1
  call void @llvm.assume(i1 %n.nonneg)
  switch i64 %n, label %loop [
  i64 9223372036854775807, label %exit
  i64 0, label %exit
  ]

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %iv.or.1 = or disjoint i64 %iv, 1
  %in.bounds = icmp slt i64 %iv.or.1, %n
  br i1 %in.bounds, label %check, label %latch

check:
  %neg = icmp slt i64 %iv, 0
  br i1 %neg, label %trap, label %body

body:
  %gep = getelementptr inbounds nuw i8, ptr %p, i64 %iv.or.1
  %v = load i8, ptr %gep, align 1
  %found = icmp eq i8 %v, 0
  br i1 %found, label %exit, label %latch

latch:
  %iv.next = add i64 %iv, 2
  %c = icmp slt i64 %iv.next, %n
  br i1 %c, label %loop, label %exit

exit:
  %r = phi i1 [ false, %entry ], [ false, %entry ], [ false, %latch ], [ true, %body ]
  ret i1 %r

trap:
  call void @llvm.trap()
  unreachable
}
